import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync, mkdtempSync } from 'node:fs';
import path from 'node:path';
import { createApp } from '../server/app.js';
import { setOwner } from '../server/auth.js';
import { executeAction, type Policy } from '../companion/policy.js';
import { config } from '../server/config.js';

mkdirSync('.local/verification', { recursive: true });
const directory = mkdtempSync(path.resolve('.local/verification/browser-'));
const service = await createApp(directory); setOwner(service.store, 'browser-test-password-only');
const address = await service.app.listen({ host: '127.0.0.1', port: 0 });
const previousOrigin=config.origin;config.origin=address;
const {chromium}=await import('playwright');
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 }, reducedMotion: 'reduce' });
const page = await context.newPage(); const errors: string[] = []; const consoleErrors: string[] = []; const failedRequests: string[] = []; const httpErrors: string[] = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', message => { if (message.type() === 'error') consoleErrors.push(message.text()); });
page.on('requestfailed', request => failedRequests.push(`${request.method()} ${request.url()} · ${request.failure()?.errorText || 'failed'}`));
page.on('response', response => { if (response.status() >= 400) httpErrors.push(`${response.status()} ${response.request().method()} ${response.url()}`); });
try {
  await page.goto(address);
  await page.getByLabel('Owner password').fill('browser-test-password-only');
  await page.getByRole('button', { name: 'Enter workspace' }).click();
  await page.getByRole('heading', { name: 'What’s on your mind?' }).waitFor();
  await page.screenshot({ path: '.local/verification/desktop-home.png', fullPage: true });
  await page.getByLabel('Message LUCIFER').fill('What is the time?');
  await page.getByRole('button', { name: 'Send message', exact: true }).click();
  await page.locator('.message.assistant').filter({ hasText: 'Asia/Kolkata' }).waitFor();
  assert.equal(service.store.list<any>('task')[0].state, 'completed');
  await page.reload(); await page.locator('.message.assistant').filter({ hasText: 'Asia/Kolkata' }).waitFor();
  await page.getByRole('button', { name: 'Toggle dark theme' }).click();
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'dark');
  await page.screenshot({ path: '.local/verification/desktop-dark.png', fullPage: true });
  await page.getByRole('button', { name: 'Toggle dark theme' }).click();
  await page.waitForFunction(() => document.documentElement.dataset.theme === 'light');

  // The responsive phone viewport issues a real scoped file command through the paired transport.
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: '.local/verification/mobile-home.png', fullPage: true });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1));
  await page.getByRole('button', { name: 'Devices', exact: true }).click();
  await page.getByRole('button', { name: 'Create pairing challenge' }).click();
  await page.locator('.notice code').waitFor();
  const challenge = (await page.locator('.notice code').textContent())!.trim();
  const capabilities = { apps: [], folders: ['project'], commands: [], actions: ['read_file'] };
  const registration = await fetch(address + '/api/companion/register', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ code: challenge, name: 'Browser test laptop transport', platform: 'linux', capabilities }) }).then(r => r.json()) as any;
  assert.ok(registration.token);
  await page.getByLabel('Target device').locator(`option[value="${registration.deviceId}"]`).waitFor({state:'attached'});
  await page.getByLabel('Target device').selectOption(registration.deviceId);
  await page.getByLabel('Action', { exact: true }).selectOption('read_file');
  await page.getByLabel('Relative path').fill('verified.txt');
  writeFileSync(path.join(directory, 'verified.txt'), 'Actual file action from a mobile-sized browser.');
  await page.getByRole('button', { name: 'Execute on Browser test laptop transport' }).click();
  for(let n=0;n<50&&!service.store.list('command').length;n++)await new Promise(r=>setTimeout(r,100));
  const poll = await fetch(address + '/api/companion/poll', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + registration.token }, body: JSON.stringify({ capabilities }) }).then(r => r.json()) as any;
  assert.equal(poll.command.action.path, 'verified.txt');
  const policy: Policy = { server: address, name: 'Test', apps: {}, folders: { project: directory }, websites: [], commands: {}, actions: ['read_file'] };
  const result = await executeAction(policy, poll.command.action, new AbortController().signal, async () => false);
  await fetch(address + '/api/companion/result', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + registration.token }, body: JSON.stringify({ commandId: poll.command.id, ok: true, result }) });
  await page.getByRole('button', { name: 'Tasks', exact: true }).click();
  await page.getByText('Device confirmed the actual result.').waitFor();
  await page.getByRole('button', { name: 'Devices', exact: true }).click();
  await page.getByLabel('Target device').selectOption(registration.deviceId);
  await page.getByLabel('Action', { exact: true }).selectOption('read_file');
  await page.getByLabel('Relative path').fill('verified.txt');
  service.store.put('device', { ...service.store.get<any>('device', registration.deviceId), lastSeen: new Date(0).toISOString() });
  await page.getByRole('button', { name: 'Execute on Browser test laptop transport' }).click();
  await page.getByRole('alert').filter({ hasText: 'offline' }).waitFor();

  await page.getByRole('button', { name: 'Files & reports', exact: true }).click();
  const csv = Buffer.from('post_id,date,format,theme,reach,views,likes,comments,shares,saves\nfixture-one,2026-09-10,reel,Practical skills,100,240,20,3,2,5\nfixture-two,2026-09-20,photo,Process,90,110,8,1,1,2');
  await page.getByLabel('Import a document, export, or logo').setInputFiles({ name: 'SYNTHETIC-BROWSER-TEST.csv', mimeType: 'text/csv', buffer: csv });
  await page.getByLabel('Actual post export').selectOption({ label: 'SYNTHETIC-BROWSER-TEST.csv' });
  await page.getByLabel('Brand', { exact: true }).fill('Browser fixture brand');
  await page.getByLabel('Instagram account').fill('@test_fixture');
  await page.getByLabel('From', { exact: true }).fill('2026-09-01');
  await page.getByLabel('Through', { exact: true }).fill('2026-09-30');
  await page.getByRole('button', { name: 'Analyse and render report' }).click();
  await page.getByLabel('Preview report').waitFor({ timeout: 90000 });
  const report = service.store.list<any>('report').at(-1); assert.equal(report.ideas.length, 6);
  await page.getByLabel('Preview report').selectOption(report.id);
  await page.getByText('Exactly 6 evidence-linked, rule-based ideas.',{exact:false}).waitFor();
  assert.equal(await page.locator('.preview-grid img').count(), 9);
  await page.getByRole('button', { name: 'I inspected all pages · approve layout' }).click();
  await page.getByText('ready', { exact: true }).waitFor();
  assert.equal(await page.getByRole('button', { name: /Send once to/ }).isDisabled(), true);
  const pdf = await context.request.get(address + '/api/files/' + report.fileId + '/download');
  assert.equal(pdf.status(), 200); assert.ok((await pdf.body()).subarray(0, 5).equals(Buffer.from('%PDF-')));

  await page.getByRole('button', { name: 'Memory', exact: true }).click();
  await page.getByLabel('Label', { exact: true }).first().fill('Report preference');
  await page.getByLabel('What to remember').fill('Keep my reports concise.');
  await page.getByRole('button', { name: 'Save memory' }).click();
  await page.getByRole('heading', { name: /Report preference/ }).waitFor();
  assert.equal(service.store.list('memory').length, 1);
  await page.getByRole('button', { name: 'Emergency stop all tasks' }).click();
  await page.getByText('Emergency stop is active. New actions are blocked.').waitFor();
  assert.equal(service.store.get<any>('control', 'emergency').stopped, true);
  await page.getByRole('button', { name: 'Resume actions' }).click();
  await page.getByRole('button', { name: 'Assistant', exact: true }).click();
  await page.getByRole('button', { name: 'Realtime', exact: true }).click();
  await page.getByRole('button', { name: 'Mute microphone and pause voice session' }).click();
  await page.getByText('microphone muted', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Stop speech and voice session' }).click();
  assert.equal(await page.getByRole('button', { name: 'Normal', exact: true }).getAttribute('class'), 'chosen');
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('button', { name: 'Configure AI provider', exact: true }).click();
  await page.getByLabel('API protocol').waitFor();
  await page.getByText('Google AI Studio:', { exact: false }).waitFor();
  const providerForm = page.locator('form.setup-card');
  const providerSelect = providerForm.getByLabel('Provider');
  const modelInput = providerForm.locator('input[name="model"]');
  const baseUrlInput = providerForm.locator('input[name="baseUrl"]');
  for (const [provider, model] of [['gemini', 'browser-gemini-model'], ['openai', 'browser-openai-model'], ['ollama', 'gemma3:1b']] as const) {
    await providerSelect.selectOption(provider);
    await modelInput.fill(model);
    if (provider === 'ollama') {
      await baseUrlInput.fill('http://127.0.0.1:11434');
    }
    await providerForm.getByRole('button', { name: 'Save and test connection' }).click();
    await page.waitForFunction(()=>document.querySelector('form.setup-card')?.getAttribute('aria-busy')==='false', undefined, {timeout:40000});
    assert.notEqual(await modelInput.inputValue(), '', `${provider} model input was lost after its recoverable connection/configuration error`);
    assert.equal(await page.getByRole('heading', { name: 'Settings' }).isVisible(), true);
  }
  await providerForm.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Skills & integrations', exact: true }).click();
  await page.getByRole('heading', { name: 'Skills & integrations' }).waitFor();
  await page.getByRole('button', { name: /Configure AI provider|Manage AI provider/, exact: true }).click();
  await page.locator('form.setup-card').getByLabel('Provider').waitFor();
  await page.locator('form.setup-card').getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Settings', exact: true }).click();
  await page.getByRole('heading', { name: 'Settings' }).waitFor();
  await page.getByRole('button', { name: /Configure AI provider|Manage AI provider/, exact: true }).click();
  await page.locator('form.setup-card').getByLabel('Provider').selectOption('gemini');
  await page.locator('form.setup-card').getByText('Google AI Studio:', { exact: false }).waitFor();
  await page.getByRole('button', { name: 'Toggle dark theme' }).click();
  assert.equal(await page.locator('form.setup-card').isVisible(), true);
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByText('Voice diagnosis', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Toggle dark theme' }).click();
  assert.deepEqual(errors, []);
  assert.deepEqual(consoleErrors.filter(message => !message.includes('status of 400')), []);
  assert.deepEqual(failedRequests, []);
  assert.ok(httpErrors.filter(error => error.includes('/api/integrations/model/config')).length >= 2);
  writeFileSync('.local/verification/browser-results.json', JSON.stringify({ passed: true, desktop: true, responsiveViewport: '390x844', realScopedFileAction: true, pdfDownload: true, sixIdeas: true, memory: true, emergencyStop: true, muteStopControls: true, aiSetupFormVisible: true, aiProviderEntryPaths: ['Settings', 'Skills & integrations'], providerChoicesWithoutCredentials: ['gemini', 'openai', 'ollama'], speechDiagnosticsVisible: true, pageErrors: errors, consoleErrors, failedRequests, expectedHttpErrors: httpErrors.filter(error => error.includes('/api/integrations/model/config')), physicalAndroid: 'not tested', microphone: 'not tested', windowsLaunch: 'not tested', liveProviders: 'not tested' }, null, 2));
  console.log('Browser journeys passed. Screenshots and detailed scope: .local/verification/browser-results.json');
} catch(error) {
  await page.screenshot({path:'.local/verification/browser-failure.png',fullPage:true}).catch(()=>{});
  throw error;
} finally { config.origin=previousOrigin;await browser.close(); await service.app.close(); }
