import assert from 'node:assert/strict';
import { mkdir, writeFile, symlink, rm, readFile } from 'node:fs/promises';
import path from 'node:path';
import { executeAction, scopedPath, type Policy } from '../companion/policy.js';
import { dpapi } from '../companion/credentials.js';
if (process.platform !== 'win32') throw new Error('Run this test with Windows Node.js');
const root = path.resolve('.local/verification/native-work');
await mkdir(path.join(root, 'approved'), { recursive: true });
await mkdir(path.join(root, 'outside'), { recursive: true });
await writeFile(path.join(root, 'approved', 'input.txt'), 'Real Windows scoped file read');
const policy: Policy = { server: 'https://test.example', name: 'Native Windows verification', apps: { node: { executable: process.execPath, args: ['--version'] } }, folders: { project: path.join(root, 'approved') }, websites: [], commands: { version: { executable: process.execPath, args: ['--version'], folders: ['project'] } }, actions: ['read_file', 'write_document', 'run_command', 'open_app'] };
const signal = new AbortController().signal;
const read: any = await executeAction(policy, { kind: 'read_file', folder: 'project', path: 'input.txt' }, signal, async () => false);
assert.equal(read.text, 'Real Windows scoped file read');
await rm(path.join(root, 'approved', 'output.txt'), { force: true });
await executeAction(policy, { kind: 'write_document', folder: 'project', path: 'output.txt', text: 'Created by the actual Windows action handler.' }, signal, async () => false);
assert.match(await readFile(path.join(root, 'approved', 'output.txt'), 'utf8'), /actual Windows/);
await assert.rejects(scopedPath(policy.folders.project, '..\\outside\\secret.txt'));
await rm(path.join(root, 'approved', 'junction'), { recursive: true, force: true });
await symlink(path.join(root, 'outside'), path.join(root, 'approved', 'junction'), 'junction');
await assert.rejects(scopedPath(policy.folders.project, 'junction\\secret.txt'), /junction/);
await assert.rejects(executeAction(policy, { kind: 'run_command', folder: 'project', command: 'version' }, signal, async () => false), /denied/);
const command: any = await executeAction(policy, { kind: 'run_command', folder: 'project', command: 'version' }, signal, async () => true);
assert.equal(command.exitCode, 0); assert.match(command.stdout, /^v\d+/);
const launch: any = await executeAction(policy, { kind: 'open_app', app: 'node' }, signal, async () => true);
assert.equal(launch.accepted, true);
const protectedValue = await dpapi('SYNTHETIC-CREDENTIAL-TEST-ONLY');
assert.notEqual(protectedValue, 'SYNTHETIC-CREDENTIAL-TEST-ONLY');
assert.equal(await dpapi(protectedValue, true), 'SYNTHETIC-CREDENTIAL-TEST-ONLY');
await writeFile('.local/verification/native-windows-results.json', JSON.stringify({ passed: true, platform: process.platform, node: process.version, scopedRead: true, createDocument: true, traversalRejected: true, junctionEscapeRejected: true, deniedCommandRejected: true, approvedCommand: true, approvedNodeAppLaunch: true, dpapiRoundTrip: true, vscode: 'not tested', physicalPhone: 'not tested' }, null, 2));
console.log('Native Windows policy, OS launch, fixed command, junction rejection and DPAPI tests passed.');
