import { parse } from 'csv-parse/sync';
import { z } from 'zod';
export const metricKeys=['reach','views','impressions','likes','comments','shares','saves'] as const;
export type Metric=typeof metricKeys[number];
export interface Post {id:string;date:string;format:string;theme:string;caption:string;metrics:Record<Metric,number|null>}
export interface Analysis {account:string;brand:string;start:string;end:string;timezone:string;source:string;retrievedAt:string;posts:Post[];metrics:Record<Metric,{total:number|null;coverage:number}>;rankBy:Metric|null;strong:Post|null;weak:Post|null;formats:{format:string;posts:number;metric:string|null;average:number|null}[];themes:{theme:string;posts:number}[];interactionRate:number|null;limitations:string[]}
export const validDate=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
export const reportInputSchema=z.object({fileId:z.uuid(),brand:z.string().min(1).max(100),account:z.string().min(1).max(100),start:z.string().refine(validDate,'Use YYYY-MM-DD'),end:z.string().refine(validDate,'Use YYYY-MM-DD'),timezone:z.string().max(80).refine(v=>{try{new Intl.DateTimeFormat('en',{timeZone:v});return true;}catch{return false;}}),logoId:z.uuid().nullable(),language:z.enum(['en','ta'])}).strict().refine(v=>v.start<=v.end,'Start must precede end');
export type ReportInput=z.infer<typeof reportInputSchema>;
export function analyzeCSV(text:string,input:ReportInput,source:string):Analysis {
 const rows=parse(text,{bom:true,columns:false,skip_empty_lines:true,max_record_size:20000}) as string[][];
 if(rows.length<2||rows.length>10001)throw new Error('CSV needs 1–10,000 post rows');const headers=rows[0].map(s=>s.trim());if(new Set(headers).size!==headers.length||headers.some(h=>!['post_id','date','format','theme','caption',...metricKeys].includes(h)))throw new Error('Duplicate or unsupported CSV column. See docs/IMPORTS.md.');for(const h of ['post_id','date','format','theme'])if(!headers.includes(h))throw new Error('Missing CSV column: '+h);
 const posts:Post[]=[];const ids=new Set<string>();
 for(let r=1;r<rows.length;r++){if(rows[r].length!==headers.length)throw new Error(`CSV row ${r+1} has inconsistent columns`);const get=(key:string)=>rows[r][headers.indexOf(key)]?.trim()||'';const postId=get('post_id'),date=get('date');if(!postId||postId.length>100||!validDate(date))throw new Error(`Row ${r+1} has invalid post_id or date`);if(ids.has(postId))throw new Error('Duplicate post_id: '+postId);ids.add(postId);const metrics={} as Record<Metric,number|null>;for(const key of metricKeys){const raw=get(key);if(raw&&!/^\d+(\.\d+)?$/.test(raw))throw new Error(`Row ${r+1}: ${key} must be a nonnegative number or empty`);const n=raw?Number(raw):null;if(n!==null&&(!Number.isSafeInteger(n)||n<0))throw new Error(`Row ${r+1}: ${key} must be a safe nonnegative integer`);metrics[key]=n;}if(!get('format')||!get('theme')||get('format').length>60||get('theme').length>120||get('caption').length>500)throw new Error(`Row ${r+1}: format/theme/caption length invalid`);if(date>=input.start&&date<=input.end)posts.push({id:postId,date,format:get('format'),theme:get('theme'),caption:get('caption'),metrics});}
 if(!posts.length)throw new Error('No posts fall inside the selected reporting period');
 const metrics={} as Analysis['metrics'];for(const key of metricKeys){const values=posts.map(p=>p.metrics[key]).filter((v):v is number=>v!==null);metrics[key]={total:values.length?values.reduce((s,v)=>s+v,0):null,coverage:values.length};}
 const rankBy=(['views','reach','impressions','likes','comments','shares','saves'] as Metric[]).find(k=>metrics[k].coverage===posts.length)??null;const ranked=rankBy?[...posts].sort((a,b)=>b.metrics[rankBy]!-a.metrics[rankBy]!):[];
 const group=new Map<string,Post[]>(),themes=new Map<string,number>();for(const p of posts){group.set(p.format,[...(group.get(p.format)||[]),p]);themes.set(p.theme,(themes.get(p.theme)||0)+1);}
 const interactionsComplete=(['likes','comments','shares','saves','reach'] as Metric[]).every(k=>metrics[k].coverage===posts.length);const denominator=metrics.reach.total;const rate=interactionsComplete&&denominator&&denominator>0?100*(metrics.likes.total!+metrics.comments.total!+metrics.shares.total!+metrics.saves.total!)/denominator:null;
 return {account:input.account,brand:input.brand,start:input.start,end:input.end,timezone:input.timezone,source,retrievedAt:new Date().toISOString(),posts,metrics,rankBy,strong:ranked[0]||null,weak:ranked.at(-1)||null,formats:[...group].map(([format,p])=>({format,posts:p.length,metric:rankBy,average:rankBy?p.reduce((s,v)=>s+v.metrics[rankBy]!,0)/p.length:null})),themes:[...themes].map(([theme,posts])=>({theme,posts})).sort((a,b)=>b.posts-a.posts),interactionRate:rate,limitations:['Based on owner-imported post-level data, not a verified live Instagram API connection.','Totals sum supplied post metrics; reach is not deduplicated account reach. Blank fields remain unavailable; zero is a real value.','Post date filters publication dates. Supplied metric observation windows are not independently verified.','Followers, follower change, unique accounts engaged, audience demographics, and account-level reach were not supplied.','No comparable previous period is included, so period-over-period changes are unavailable.','Interpretations describe this sample only. Video ideas are proposals, not promised outcomes.']};
}
export interface Idea {title:string;reason:string;hook:string;format:string;duration:string;scenes:string[];voiceover:string;caption:string;cta:string;metric:string}
export function sixIdeas(a:Analysis,language:'en'|'ta'):Idea[] {
 const post=a.strong||a.posts[0],theme=post.theme;const evidence=a.rankBy&&a.strong?`Post ${post.id} (${theme}) recorded ${post.metrics[a.rankBy]} ${a.rankBy}, highest in ${a.posts.length} imported posts.`:`Theme “${theme}” appears in the imported dataset; comparative ranking is unavailable.`;
 const titles=['One useful lesson','Behind the process','Three mistakes to avoid','A real question, answered','Before and after, explained','One idea, two approaches'];
 const taTitles=['ஒரு பயனுள்ள பாடம்','செயல்முறைக்குப் பின்னால்','தவிர்க்க வேண்டிய மூன்று தவறுகள்','ஒரு கேள்விக்குப் பதில்','முன்பும் பின்பும் விளக்கம்','ஒரே கருத்து, இரு அணுகுமுறைகள்'];
 return titles.map((title,i)=>({title:language==='ta'?`${taTitles[i]} · ${theme}`:`${a.brand}: ${title} on ${theme}`,reason:language==='ta'?`இறக்குமதி ஆதாரம்: ${evidence} இதே கருப்பொருளை புதிய கோணத்தில் சோதிக்கும் பரிந்துரை.`:`${evidence} This proposal tests a distinct ${title.toLowerCase()} angle rather than assuming the same result will repeat.`,hook:language==='ta'?`“${theme} பற்றி நீங்கள் கவனிக்காத ஒரு விஷயம்…”`:`“${theme}: here’s the ${i===2?'mistake':i===3?'question':'detail'} most people overlook.”`,format:language==='ta'?`Reel · ${i%2?'செயல்விளக்கம்':'நேரடிப் பேச்சு'} + subtitles`:`Reel · ${i%2?'process demonstration':'talking head'} + readable subtitles`,duration:i===2?'40–50 seconds':'25–35 seconds',scenes:language==='ta'?[`0–3s: ${theme} கேள்வியுடன் தொடங்கு.`,`3–10s: ${a.brand} தொடர்பான உண்மையான உதாரணத்தைக் காட்டு.`,`10–22s: ${taTitles[i]} — முக்கிய விளக்கத்தைச் சொல்.`,`22–30s: முடிவையும் ஒரு செயலழைப்பையும் காட்டு.`]:[`0–3s: Open with the ${theme} hook and one close-up visual.`,`3–10s: Show a real ${a.brand} example; identify what the viewer is looking at.`,`10–22s: ${i===2?'Explain three specific pitfalls':i===3?'Answer one question without unsupported claims':i===4?'Show the starting state and observable change':i===5?'Compare two approaches using the same criteria':i===1?'Demonstrate the process in three steps':'Teach one actionable lesson'}; separate source facts from your advice.`,`22–30s: Recap the takeaway and display one clear call to action.`],voiceover:language==='ta'?`${theme} பற்றிய உண்மையான உதாரணம், செயல்முறை, கற்ற பாடம் ஆகியவற்றை ${a.brand} பாணியில் விளக்கவும். தரவில் இல்லாத முடிவுகளைச் சொல்ல வேண்டாம்.`:`Explain the ${theme} example in ${a.brand}'s voice: what happened, how it works, and what the viewer can try. Use your actual experience; do not claim metrics or testimonials absent from the source.`,caption:language==='ta'?`${theme} — ${a.brand} இன் ஒரு நடைமுறை விளக்கம். உங்கள் அனுபவம் என்ன?`:`${theme}, made practical. A ${a.brand} perspective on ${title.toLowerCase()}. What would you try?`,cta:language==='ta'?i%2?'உங்கள் கேள்வியை கருத்தில் எழுதுங்கள்.':'பின்னர் பார்க்க சேமிக்கவும்.':i%2?'Leave one question for the next video.':'Save this for your next attempt.',metric:language==='ta'?`${i%2?'comments / reach':'saves / reach'} × 100; இரண்டும் கிடைத்தால் மட்டும்; reach=0 என்றால் கணக்கிட வேண்டாம்.`:`${i%2?'Comments':'Saves'} / supplied post reach × 100, only when both are available and reach > 0. Compare at the same age after publishing.`}));
}
