import type { FastifyInstance,FastifyRequest } from 'fastify';
import { randomBytes } from 'node:crypto';
import { z } from 'zod';
import { Store,id,now } from './store.js';
import { hash,redact } from './auth.js';
import { Tasks } from './tasks.js';
import { deviceActionSchema,type Device,type DeviceCommand,type Settings } from '../shared/contracts.js';
export interface DeviceTransport { enqueue(deviceId:string,action:unknown):DeviceCommand; revoke(deviceId:string):void }
const capabilitySchema=z.object({apps:z.array(z.string().max(60)).max(100),folders:z.array(z.string().max(60)).max(30),commands:z.array(z.string().max(60)).max(30),actions:z.array(z.string().max(60)).max(30)}).strict();
export class Devices implements DeviceTransport {
  constructor(public store:Store,public tasks:Tasks,public settings:()=>Settings) {
    for(const command of store.list<DeviceCommand>('command'))if(['pending','claimed'].includes(command.status)){store.put('command',{...command,status:'failed',result:{error:'Server restarted; command is not replayed.'}});tasks.update(command.taskId,'partially_completed',undefined,'Server restarted. Check the laptop before submitting a fresh action.');}
  }
  enabled(){if(this.store.get<{stopped:boolean}>('control','emergency')?.stopped)throw new Error('Emergency stop is active');if(!this.settings().permissions.devices)throw new Error('Device permission is disabled');}
   enqueue(deviceId:string,input:unknown,ownerApproved=false,parentTaskId?:string) {
    this.enabled();const action=deviceActionSchema.parse(input);const device=this.store.get<Device>('device',deviceId);
    if(!device||device.revoked)throw new Error('Device is not paired or has been revoked');
    if(Date.now()-Date.parse(device.lastSeen)>15000)throw new Error('The selected device is offline. No command was queued.');
    if(this.store.list<DeviceCommand>('command').some(c=>c.deviceId===deviceId&&['pending','claimed'].includes(c.status)))throw new Error('This device already has an active command. Complete or cancel it first.');
    if(!device.capabilities.actions.includes(action.kind))throw new Error('Device does not support this action');
    if('folder'in action&&!device.capabilities.folders.includes(action.folder))throw new Error('Folder alias is not approved');
    if(action.kind==='open_app'&&!device.capabilities.apps.includes(action.app))throw new Error('Application is not approved');
    if(action.kind==='run_command'&&!device.capabilities.commands.includes(action.command))throw new Error('Command is not approved');
    const task=this.tasks.create(`${device.name}: ${action.kind.replaceAll('_',' ')}`,'running');this.tasks.event(task.id,'Sending authorized structured action to '+device.name+'.');
    return this.store.put('command',{id:id(),taskId:task.id,deviceId,action,status:'pending',ownerApproved,parentTaskId,expiresAt:new Date(Date.now()+20000).toISOString()} as DeviceCommand);
  }
  revoke(deviceId:string){const d=this.store.get<Device>('device',deviceId);if(d)this.store.put('device',{...d,revoked:true});const c=this.store.get<any>('credential',deviceId);if(c)this.store.remove('credential',deviceId);for(const cmd of this.store.list<DeviceCommand>('command'))if(cmd.deviceId===deviceId&&['pending','claimed'].includes(cmd.status)){this.store.put('command',{...cmd,status:'cancelled'});this.tasks.cancel(cmd.taskId);}}
  expirePending(time=Date.now()) {for(const command of this.store.list<DeviceCommand>('command'))if(command.status==='pending'&&Date.parse(command.expiresAt)<=time){this.store.put('command',{...command,status:'failed',result:{error:'Device did not claim the command before its deadline. It was not executed or replayed.'}});this.tasks.update(command.taskId,'failed',undefined,'Device command expired before being claimed. Submit a fresh request when the laptop is online.');}}
  authenticate(req:FastifyRequest):Device {const token=req.headers.authorization?.replace(/^Bearer /,'');if(!token)throw Object.assign(new Error('Unauthorized device'),{statusCode:401});const credential=this.store.list<{id:string;hash:string}>('credential').find(c=>c.hash===hash(token));const device=credential&&this.store.get<Device>('device',credential.id);if(!device||device.revoked)throw Object.assign(new Error('Device credential invalid or revoked'),{statusCode:401});return device;}
  register(app:FastifyInstance){
    app.post('/api/devices/pairing',async()=>{this.enabled();const code=randomBytes(16).toString('base64url');const expiresAt=new Date(Date.now()+300000).toISOString();this.store.put('pairing',{id:hash(code),expiresAt});return {code,expiresAt};});
    app.post('/api/companion/register',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(req)=>{const b=z.object({code:z.string().min(20).max(80),name:z.string().min(1).max(80),platform:z.enum(['win32','linux','darwin']),capabilities:capabilitySchema}).strict().parse(req.body);this.enabled();const challenge=this.store.get<{expiresAt:string}>('pairing',hash(b.code));if(!challenge||Date.parse(challenge.expiresAt)<Date.now())throw Object.assign(new Error('Pairing challenge expired or already consumed'),{statusCode:401});this.store.remove('pairing',hash(b.code));const device:Device={id:id(),name:b.name,platform:b.platform,capabilities:b.capabilities,lastSeen:now(),revoked:false};const token=randomBytes(32).toString('base64url');this.store.put('device',device);this.store.put('credential',{id:device.id,hash:hash(token)});return {deviceId:device.id,token};});
    app.post('/api/companion/poll',async(req)=>{const device=this.authenticate(req);const body=z.object({capabilities:capabilitySchema}).parse(req.body);this.store.put('device',{...device,lastSeen:now(),capabilities:body.capabilities});const stopped=this.store.get<{stopped:boolean}>('control','emergency')?.stopped||!this.settings().permissions.devices;const cancelled=this.store.list<DeviceCommand>('command').filter(c=>c.deviceId===device.id&&c.status==='cancelled').map(c=>c.id);let next:DeviceCommand|undefined;for(const c of this.store.list<DeviceCommand>('command'))if(c.deviceId===device.id&&c.status==='pending'){if(stopped||Date.parse(c.expiresAt)<Date.now()){this.store.put('command',{...c,status:'failed'});this.tasks.update(c.taskId,'failed',undefined,'Command expired or emergency stop active. It was not replayed.');}else if(!next){next={...c,status:'claimed'};this.store.put('command',next);this.tasks.event(c.taskId,'Laptop claimed the command.');}}return {command:next||null,stopped,cancelled};});
    app.post('/api/companion/result',async(req)=>{const device=this.authenticate(req);const b=z.object({commandId:z.uuid(),ok:z.boolean(),result:z.record(z.string(),z.unknown())}).strict().parse(req.body);const command=this.store.get<DeviceCommand>('command',b.commandId);if(!command||command.deviceId!==device.id)throw Object.assign(new Error('Command does not belong to this device'),{statusCode:403});if(command.status==='completed'||command.status==='failed')return {ok:true,duplicate:true};if(command.status!=='claimed'&&command.status!=='cancelled')throw new Error('Command was not claimed');const result=JSON.parse(redact(JSON.stringify(b.result)));if(command.status==='cancelled'){this.tasks.event(command.taskId,'Device reported an outcome after cancellation: '+JSON.stringify(result).slice(0,500));this.store.put('command',{...command,result});}else{this.store.put('command',{...command,status:b.ok?'completed':'failed',result});this.tasks.update(command.taskId,b.ok?'completed':'failed',result,b.ok?undefined:String(result.error||'Device action failed'));this.tasks.event(command.taskId,b.ok?'Device confirmed the actual result.':'Device reported failure.');}return {ok:true};});
    app.post('/api/devices/:id/action',async(req)=>{const {id}=req.params as {id:string};return this.enqueue(id,req.body,true);});
    app.delete('/api/devices/:id',async(req)=>{this.revoke((req.params as {id:string}).id);return {ok:true};});
  }
}
