import path from 'node:path';
import type {Assistant} from './assistant.js';
import type {ToolContext} from '../shared/contracts.js';
export function registerLocalActions(assistant:Assistant){
 assistant.localActions.push(async(text,ctx,record)=>{
  const call=async(name:string,input:unknown)=>{ctx.signal.throwIfAborted();const tool=assistant.tools.find(tool=>tool.name===name);if(!tool)throw new Error('Local capability is unavailable');if(tool.permission&&!assistant.settings().permissions[tool.permission])throw new Error(tool.permission+' permission is disabled');const validated=tool.schema.parse(input);assistant.tasks.event(ctx.taskId,'Executing local '+name.replaceAll('_',' '));const output:any=await tool.run(validated,ctx);record(name,validated,output);ctx.signal.throwIfAborted();return output;};
  const reminder=text.match(/^remind me at (\d{4}-\d{2}-\d{2}T\d{2}:\d{2}) in ([A-Za-z_\/-]+) to (.{1,300}?)(?:;\s*then cancel (?:it|that test reminder))?[.!\s]*$/i);
  if(reminder){const saved=await call('manage_voice_reminder',{operation:'save',title:reminder[3],localTime:reminder[1],timezone:reminder[2],recurrence:'none'});if(/;\s*then cancel/i.test(text)){const cancelled=await call('manage_voice_reminder',{operation:'cancel',reminderId:saved.id});return {reply:'Created and cancelled the in-app test reminder: '+cancelled.title+' · '+cancelled.id};}return {reply:'Saved in-app reminder: '+saved.title+' · '+saved.at+' · '+saved.timezone+'\nReminder ID: '+saved.id};}
  const relative=text.match(/^remind me in (\d{1,4}) (minutes?|hours?) to (.{1,300})$/i);if(relative){const minutes=Number(relative[1])*(relative[2].toLowerCase().startsWith('hour')?60:1);if(minutes<1||minutes>10080)throw new Error('Local relative reminders support 1 minute to 7 days');const at=new Date(Math.ceil((Date.now()+minutes*60000)/60000)*60000),parts=new Intl.DateTimeFormat('en-CA',{timeZone:ctx.settings.timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(at),get=(key:string)=>parts.find(part=>part.type===key)!.value;const saved=await call('manage_voice_reminder',{operation:'save',title:relative[3],localTime:`${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`,timezone:ctx.settings.timezone,recurrence:'none'});return {reply:'Saved in-app reminder at minute precision: '+saved.title+' · '+saved.at+' · '+saved.timezone+'\nReminder ID: '+saved.id};}
  if(/^list(?: my)? reminders[.!?\s]*$/i.test(text)){const reminders=await call('manage_voice_reminder',{operation:'list'});return {reply:reminders.length?reminders.map((reminder:any)=>`${reminder.title} · ${reminder.status} · ${reminder.at} · ${reminder.id}`).join('\n'):'No reminders saved.'};}
  const cancel=text.match(/^cancel reminder ([a-f0-9-]{36})[.!\s]*$/i);if(cancel){const value=await call('manage_voice_reminder',{operation:'cancel',reminderId:cancel[1]});return {reply:'Cancelled reminder: '+value.title};}
  if(!ctx.nativeDeviceId)return;
  const note=text.match(/^(?:create|write) (?:a )?note ([a-z0-9_-]{1,60})\/([^\s:]{1,300}):\s*([\s\S]+?);\s*then find and read it[.!\s]*$/i);
  if(note){const folder=note[1],relative=note[2],contents=note[3];await call('windows_write_document',{folder,path:relative,text:contents});const found=await call('windows_find_files',{folder,query:path.posix.basename(relative)});if(!found.matches.includes(relative))throw new Error('Created note was not found in the approved search scope');const read=await call('windows_read_file',{folder,path:relative});if(read.text!==contents)throw new Error('Created note contents did not match the read-back');assistant.store.put('native_context',{id:ctx.nativeDeviceId,note:{folder,path:relative,text:read.text}});return {reply:'Created, found and read '+folder+'/'+relative+'.\n'+read.text};}
  if(/^(?:read that note again|what was in that note|what was (?:the )?(?:last|previous) note)[.!?\s]*$/i.test(text)){const note=assistant.store.get<any>('native_context',ctx.nativeDeviceId)?.note;if(!note)return {reply:'No verified note reference in this laptop conversation yet. Specify its approved folder and filename.'};const read=await call('windows_read_file',{folder:note.folder,path:note.path});return {reply:note.folder+'/'+note.path+'\n'+read.text};}
  const website=text.match(/^open (https:\/\/\S+) and (?:tell me what you see|report what you see|read the page)[.!?\s]*$/i);
  const search=text.match(/^search the web for (.{1,300})$/i);
  if(website||search){const observed=await call('windows_browser_action',website?{operation:'open',url:website[1]}:{operation:'search',query:search![1]});if(observed.privateLoginRequired)return {reply:'Complete login/MFA privately in the dedicated browser, then ask me to observe it again.',needsInput:true};if(!observed.text)throw new Error('No readable browser page was observed');return {reply:observed.title+'\n\nObserved page text:\n'+observed.text.slice(0,1800)+'\n\nSource: '+observed.url+'\nObserved: '+observed.observedAt};}
  if(/^discover installed (?:apps|applications)(?: and list their launch aliases)?[.!?\s]*$/i.test(text)){const found=await call('windows_discover_apps',{});return {reply:'Observed installed launch targets:\n'+found.apps.map((app:any)=>app.name+' · '+app.id).join('\n')+'\nApprove additional launch aliases in Permissions.'};}
 });
}
