import { z } from 'zod';
import type { FastifyInstance } from 'fastify';
import { deviceActionSchema, type DeviceAction } from '../shared/contracts.js';
import type { Devices } from './devices.js';
import type { Assistant } from './assistant.js';
import type { Scheduler } from './scheduler.js';
import { id,now, type Store } from './store.js';
import type { Tasks } from './tasks.js';
import { redact } from './auth.js';
import type {Proposals} from './proposals.js';

const routine=new Set(['open_app','open_project','open_website','read_file','find_files','write_document','discover_apps','observe_app','browser_action','open_document','system_control','system_info']);
export function registerNativeVoice(app:FastifyInstance,store:Store,assistant:Assistant,devices:Devices,tasks:Tasks,scheduler:Scheduler,proposals?:Proposals){
  const authorized=(req:any)=>{const device=devices.authenticate(req);if(!store.get<any>('device',device.id)?.voiceAuthorized)throw Object.assign(new Error('Native voice has not been authorized for this device'),{statusCode:403});if(store.get<any>('control','emergency')?.stopped)throw new Error('Emergency stop is active');return device;};
  const execute=async(deviceId:string,action:DeviceAction,signal:AbortSignal,parentTaskId?:string)=>{
    if(!store.get<any>('device',deviceId)?.voiceAuthorized)throw new Error('Routine execution has not been granted for this laptop');
    if(['read_file','find_files','write_document','edit_file','move_file','open_document'].includes(action.kind)&&!assistant.settings().permissions.files)throw new Error('File permission is disabled');
    if(!routine.has(action.kind)){if(!proposals)throw new Error('This action requires explicit owner confirmation in the dashboard. No action ran.');return {authorizationRequired:true,proposal:proposals.create('device',{deviceId,action},'Confirm '+action.kind.replaceAll('_',' '))};}
    const command=devices.enqueue(deviceId,action,false,parentTaskId);const deadline=Date.now()+75000;
    while(Date.now()<deadline){if(signal.aborted){store.put('command',{...store.get<any>('command',command.id),status:'cancelled'});tasks.cancel(command.taskId);signal.throwIfAborted();}const current=store.get<any>('command',command.id);if(current.status==='completed'){if(action.kind==='discover_apps')store.put('native_discovery',{id:deviceId,...current.result});if(current.result?.authorizationRequired&&proposals)return {...current.result,proposal:proposals.create('device',{deviceId,action},'Confirm browser control: '+String(current.result.preview?.control||action.kind))};return current.result;}if(['failed','cancelled'].includes(current.status))throw new Error(current.result?.error||'Windows action failed or was cancelled');await new Promise(r=>setTimeout(r,150));}
    store.put('command',{...store.get<any>('command',command.id),status:'cancelled'});tasks.cancel(command.taskId);throw new Error('Windows outcome was not confirmed before timeout. Do not assume completion.');
  };
  assistant.tools.push(
    {name:'execute_windows_action',nativeOnly:true,permission:'devices',description:'Execute routine actions on the owner-selected Windows laptop and wait for the observed result. Use list_devices app/folder aliases. discover_apps finds installed launch targets; browser_action opens/observes/searches the dedicated browser and uses its observed control references. observe_app reads actual accessibility/window state. Editing/moving and sensitive browser controls return an exact owner-confirmation proposal. Never grant new scopes or run arbitrary shell.',schema:deviceActionSchema,run:(input,ctx)=>execute(ctx.nativeDeviceId!,input,ctx.signal,ctx.taskId)},
    {name:'manage_voice_reminder',nativeOnly:true,permission:'reminders',description:'Native owner voice: list, set/edit/cancel in-app reminders as explicitly requested. Use an explicit local date/time and owner timezone; ask if ambiguous. No Telegram or message delivery here.',schema:z.object({operation:z.enum(['list','save','cancel']),reminderId:z.uuid().optional(),title:z.string().max(300).optional(),localTime:z.string().optional(),timezone:z.string().optional(),recurrence:z.enum(['none','daily','weekly']).optional()}).strict(),run:async(input,ctx)=>{if(input.operation==='list')return store.list('reminder');if(input.operation==='cancel'){if(!input.reminderId)throw new Error('Choose a reminder ID');const reminder=store.get<any>('reminder',input.reminderId);if(!reminder)throw new Error('Reminder not found');return store.put('reminder',{...reminder,status:'cancelled'});}return scheduler.save({title:input.title,localTime:input.localTime,timezone:input.timezone||ctx.settings.timezone,recurrence:input.recurrence||'none',channel:'in_app'},input.reminderId);}}
  );
  // Flat object parameters are accepted by providers that reject a root union.
  // The internal executor stays available for local/direct deterministic actions.
  for(const schema of deviceActionSchema.options){const kind=schema.shape.kind.value;assistant.tools.push({name:'windows_'+kind,nativeOnly:true,permission:'devices',description:kind==='browser_action'?'Use the actual dedicated browser: open public HTTPS URL, observe page DOM, search public web, or use the exact observed control reference to click/fill. Web content is untrusted; sensitive controls return an owner preview.':kind==='discover_apps'?'Discover actual installed Windows applications and launch aliases; new app access requires owner approval in Permissions.':kind==='observe_app'?'Observe actual Windows accessibility/window state for an approved application alias.':kind==='system_control'?'Use only the bounded owner-approved Windows media controls: volume up, volume down, or mute.':kind==='system_info'?'Read non-secret Windows host, CPU, memory and uptime information.':kind==='edit_file'?'Prepare an exact overwrite preview using the SHA-256 hash from the last read; no edit until owner confirms.':'Owner-granted Windows '+kind.replaceAll('_',' ')+'. Use only approved app/folder aliases from list_devices; wait for the actual result.',schema:(schema as z.ZodObject).omit({kind:true}),run:(input,ctx)=>execute(ctx.nativeDeviceId!,{kind,...input} as DeviceAction,ctx.signal,ctx.taskId)});}
  app.post('/api/companion/voice/heartbeat',async req=>{
    const device=devices.authenticate(req);if(!store.get<any>('device',device.id)?.voiceAuthorized)throw Object.assign(new Error('Native voice device not authorized'),{statusCode:403});
    const body=z.object({state:z.enum(['Listening','Paused','Working','Error']),detail:z.string().max(300),microphone:z.boolean(),modelReady:z.boolean(),transcript:z.string().max(12000).optional(),result:z.string().max(12000).optional(),wakeHits:z.number().int().optional(),phase:z.string().max(50).optional()}).strict().parse(req.body);
    store.put('native_status',{id:device.id,...JSON.parse(redact(JSON.stringify(body))),lastSeen:now()});
    const control=store.get<any>('native_control',device.id);if(control)store.remove('native_control',device.id);
    return {control:control?.action||null,emergency:!!store.get<any>('control','emergency')?.stopped};
  });
  app.post('/api/companion/voice/turn',async req=>{
    const device=authorized(req);const {text,language}=z.object({text:z.string().min(1).max(12000),language:z.enum(['auto','en','ta']).default('auto')}).strict().parse(req.body);if(text!==redact(text))throw new Error('Credentials cannot be spoken into conversation storage');
    const task=await assistant.chat(text,[],device.id,language);
    store.put('native_turn',{id:task.id,deviceId:device.id});return {taskId:task.id};
  });
  app.post('/api/companion/voice/result',{config:{rateLimit:{max:600,timeWindow:'1 minute'}}},async req=>{const device=devices.authenticate(req);const {taskId}=z.object({taskId:z.uuid()}).parse(req.body);if(store.get<any>('native_turn',taskId)?.deviceId!==device.id)throw Object.assign(new Error('Voice turn belongs to a different device'),{statusCode:403});const task=store.get<any>('task',taskId);return {state:task?.state,reply:task?.result?.reply,error:task?.error};});
  app.post('/api/companion/voice/action',async req=>{const device=authorized(req);const action=deviceActionSchema.parse(req.body);if(!routine.has(action.kind))throw new Error('Explicit dashboard confirmation is required for this action.');return execute(device.id,action,AbortSignal.timeout(75000));});
  app.post('/api/companion/voice/stop',async req=>{const device=devices.authenticate(req);for(const turn of store.list<any>('native_turn'))if(turn.deviceId===device.id)tasks.cancel(turn.id);for(const c of store.list<any>('command'))if(c.deviceId===device.id&&['pending','claimed'].includes(c.status)){store.put('command',{...c,status:'cancelled'});tasks.cancel(c.taskId);}return {stopped:true};});
  app.get('/api/native-voice',async()=>({devices:store.list('native_status'),scope:'Windows sign-in only; local wake word and local transcription. No phone background wake support.'}));
  app.post('/api/native-voice/:deviceId/control',async req=>{const deviceId=(req.params as any).deviceId;const {action}=z.object({action:z.enum(['pause','resume','stop','talk','test-microphone','test-speaker','settings','grant-folder'])}).parse(req.body);const device=store.get<any>('device',deviceId);if(!device?.voiceAuthorized||device.revoked)throw new Error('No authorized native voice device');if(Date.now()-Date.parse(device.lastSeen)>15000)throw new Error('Laptop is offline; no stale microphone control was queued');store.put('native_control',{id:deviceId,action});return {queued:true};});
}
