import type { FastifyInstance } from 'fastify';
import { chromium } from 'playwright';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { analyzeCSV,sixIdeas,reportInputSchema,type ReportInput,type Analysis,type Idea } from './analytics.js';
import { Files,extractPDF } from './files.js';
import { Store,id,now } from './store.js';
import { Tasks } from './tasks.js';
import type { Assistant } from './assistant.js';
import type { StoredFile } from '../shared/contracts.js';
import { rasterPDF } from './pdf-render.js';
export interface Report {id:string;input:ReportInput;analysis:Analysis;ideas:Idea[];fileId:string;pages:number;status:'awaiting_visual_review'|'ready';createdAt:string;reviewedAt?:string}
const escape=(value:unknown)=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export class Reports {
 constructor(public store:Store,public files:Files,public tasks:Tasks,public assistant:Assistant){}
 enabled(){if(!this.assistant.settings().permissions.reports)throw new Error('Report permission is disabled');if(this.store.get<{stopped:boolean}>('control','emergency')?.stopped)throw new Error('Emergency stop is active');}
 async generate(input:ReportInput,taskId:string,signal:AbortSignal) {
   this.enabled();this.files.enabled();this.tasks.event(taskId,'Reading imported account data.');const csv=this.store.get<StoredFile>('file',input.fileId);if(csv?.type!=='text/csv'||!csv.text)throw new Error('Select an imported CSV export');const analysis=analyzeCSV(csv.text,input,csv.name);signal.throwIfAborted();this.tasks.event(taskId,'Comparing supplied post performance and format averages.');const ideas=sixIdeas(analysis,input.language);if(ideas.length!==6)throw new Error('Exactly six ideas are required');this.tasks.event(taskId,'Preparing six brand-tailored, evidence-based proposals.');
   let logo:string|undefined;if(input.logoId){const file=this.store.get<StoredFile>('file',input.logoId);if(!file||!['image/png','image/jpeg'].includes(file.type))throw new Error('Logo must be an uploaded PNG or JPEG');logo=`data:${file.type};base64,${(await this.files.read(file.id)).toString('base64')}`;}
   const reportId=id();const html=await reportHTML(analysis,ideas,input.language,logo);signal.throwIfAborted();this.enabled();this.tasks.event(taskId,'Rendering the PDF with embedded English and Tamil fonts.');
   const browser=await chromium.launch({headless:true});const abort=()=>{void browser.close().catch(()=>{});};signal.addEventListener('abort',abort,{once:true});
   try{const page=await browser.newPage({viewport:{width:794,height:1123},deviceScaleFactor:1});await page.route('**/*',route=>route.abort());await page.setContent(html,{waitUntil:'load'});await page.evaluate(()=>document.fonts.ready);const overflow=await page.locator('.sheet').evaluateAll(sheets=>sheets.map((s,i)=>({page:i+1,overflow:[...s.querySelectorAll('.content *')].some(e=>{const r=e.getBoundingClientRect(),bound=s.querySelector('footer')!.getBoundingClientRect();return r.bottom>bound.top-12||r.right>s.getBoundingClientRect().right-35;})})).filter(v=>v.overflow));if(overflow.length)throw new Error('PDF layout overflow on pages '+overflow.map(p=>p.page).join(', '));
     const pdf=await page.pdf({format:'A4',printBackground:true,preferCSSPageSize:true});signal.throwIfAborted();const text=await extractPDF(pdf);if(!text.includes(analysis.account))throw new Error('Rendered PDF text verification failed');const file=await this.files.save(`${input.brand}-Instagram-${input.end}.pdf`,'application/pdf',pdf,text,true,reportId);let pages:number;try{pages=await rasterPDF(pdf,path.join(this.files.directory,file.id),signal,await page.locator('.sheet').count());}catch(e){await this.files.delete(file.id);throw e;}const report:Report={id:reportId,input,analysis,ideas,fileId:file.id,pages,status:'awaiting_visual_review',createdAt:now()};this.store.put('report',report);this.tasks.event(taskId,`PDF text and layout checks passed. ${pages} actual PDF page previews are available; visual approval is required before delivery.`);return {reportId,fileId:file.id,pages,status:report.status};
   }finally{signal.removeEventListener('abort',abort);await browser.close();}
 }
 register(app:FastifyInstance){
   app.post('/api/reports',async(req)=>{const input=reportInputSchema.parse(req.body);this.enabled();return this.tasks.run('Instagram report · '+input.brand,(task,signal)=>this.generate(input,task.id,signal));});
   app.get('/api/reports',async()=>this.store.list<Report>('report'));
   app.get('/api/reports/:id',async(req)=>{const report=this.store.get<Report>('report',(req.params as {id:string}).id);if(!report)throw new Error('Report not found');return report;});
   app.get('/api/reports/:id/pages/:page',async(req,reply)=>{const {id:reportId,page:p}=req.params as {id:string;page:string};const report=this.store.get<Report>('report',reportId),page=Number(p);if(!report||!Number.isInteger(page)||page<1||page>report.pages)throw new Error('Page not found');this.files.enabled();return reply.type('image/png').header('Cache-Control','no-store').send(await readFile(path.join(this.files.directory,`${report.fileId}-page-${page}.png`)));});
   app.post('/api/reports/:id/approve',async(req)=>{this.enabled();const report=this.store.get<Report>('report',(req.params as {id:string}).id);if(!report)throw new Error('Report not found');return this.store.put('report',{...report,status:'ready',reviewedAt:now()});});
   this.assistant.tools.push({name:'create_report',description:'Create a local PDF from an attached Instagram CSV, with exactly six rule-based brand-tailored ideas. Requires explicit account, brand and dates from the user. Never sends it. Returns previews for visual review.',schema:reportInputSchema,permission:'reports',run:async(input,ctx)=>{if(!ctx.fileIds.includes(input.fileId))throw new Error('CSV must be attached to this instruction');return this.generate(input,ctx.taskId,ctx.signal);}});
 }
}
export async function reportHTML(a:Analysis,ideas:Idea[],language:'en'|'ta',logo?:string) {
 const latin=(await readFile(path.resolve('node_modules/@fontsource/inter/files/inter-latin-400-normal.woff2'))).toString('base64');const tamil=(await readFile(path.resolve('node_modules/@fontsource/noto-sans-tamil/files/noto-sans-tamil-tamil-400-normal.woff2'))).toString('base64');
 const ta=language==='ta',h=(en:string,t:string)=>ta?t:en;const brand=logo?`<img class="logo" src="${logo}"/>`:'<div class="brand">✦ LUCIFER</div>';
 const summary=`${a.posts.length} ${h('posts supplied','பதிவுகள் வழங்கப்பட்டுள்ளன')}. ${a.strong?`${h('Highest by','அதிகமான')} ${a.rankBy}: ${a.strong.id} · ${a.strong.theme}.`:h('Comparative ranking unavailable.','ஒப்பீட்டுத் தரவரிசை கிடைக்கவில்லை.')}`;
 const metricRows=Object.entries(a.metrics).map(([key,m])=>`<tr><td>${escape(key)}</td><td>${m.total===null?h('Unavailable','கிடைக்கவில்லை'):m.total.toLocaleString('en-IN')}</td><td>${m.coverage}/${a.posts.length}</td></tr>`).join('');
 const pages:string[]=[];
 pages.push(`${brand}<div class="kicker">${h('IMPORTED INSTAGRAM INTELLIGENCE','இறக்குமதி Instagram பகுப்பாய்வு')}</div><h1>${h('A clearer picture.\nA practical next move.','தெளிவான பார்வை.\nநடைமுறை அடுத்த படி.')}</h1><p class="subtitle">${escape(a.brand)} · ${escape(a.account)}</p><p>${escape(a.start)} → ${escape(a.end)} · ${escape(a.timezone)}</p><h2>${h('Executive summary','சுருக்கம்')}</h2><p>${escape(summary)}</p><p>${h('This report uses only the supplied export. The following six video ideas are evidence-linked, rule-based creative proposals. They are not promises of future performance.','இந்த அறிக்கை வழங்கப்பட்ட தரவை மட்டுமே பயன்படுத்துகிறது. ஆறு வீடியோ யோசனைகள் ஆதாரத்துடன் இணைக்கப்பட்ட படைப்புப் பரிந்துரைகள்; எதிர்கால முடிவுகளுக்கான உறுதிமொழி அல்ல.')}</p><h2>${h('Available metrics','கிடைக்கும் அளவீடுகள்')}</h2><table><thead><tr><th>${h('Source metric','மூல அளவீடு')}</th><th>${h('Sum of supplied posts','பதிவுகளின் கூட்டுத்தொகை')}</th><th>${h('Coverage','தரவு கிடைப்பு')}</th></tr></thead><tbody>${metricRows}</tbody></table><p class="note">${h('Coverage = posts with a supplied value / posts in this period. Post reach totals are not unique account reach.','தரவு கிடைப்பு = மதிப்பு வழங்கப்பட்ட பதிவுகள் / காலப்பகுதிப் பதிவுகள். reach கூட்டுத்தொகை தனித்துவமான account reach அல்ல.')}</p>`);
 pages.push(`${brand}<div class="kicker">${h('OBSERVATIONS & INTERPRETATIONS','கவனிப்புகள் & விளக்கங்கள்')}</div><h1>${h('What the data says.','தரவு சொல்வது.')}</h1><h2>${h('What is working · factual observation','சிறப்பாக இருப்பது · உண்மைக் கவனிப்பு')}</h2><p>${a.strong?escape(`${a.strong.id} · ${a.strong.theme} · ${a.strong.metrics[a.rankBy!]} ${a.rankBy}`):h('Ranking unavailable: no common supplied metric.','பொதுவான அளவீடு இல்லை; தரவரிசை கிடைக்கவில்லை.')}</p><h2>${h('What needs improvement · observation','மேம்படுத்த வேண்டியது · கவனிப்பு')}</h2><p>${a.weak?escape(`${a.weak.id} · ${a.weak.theme} · ${a.weak.metrics[a.rankBy!]} ${a.rankBy}`):h('Insufficient comparable data.','ஒப்பிடக்கூடிய தரவு போதவில்லை.')}</p><p>${h('A lower metric is not proof of poor creative quality. Timing, distribution and missing metrics can affect interpretation. Test a clearer opening hook before changing the whole strategy.','குறைந்த அளவீடு படைப்புத் தரம் குறைவு என்பதற்கான சான்றல்ல. நேரம், விநியோகம், விடுபட்ட அளவீடுகள் விளக்கத்தைப் பாதிக்கும். முதலில் தெளிவான தொடக்கத்தைச் சோதிக்கவும்.')}</p><h2>${h('Performance by format','வடிவத்தின் செயல்திறன்')}</h2><table><thead><tr><th>Format</th><th>Posts</th><th>${escape(a.rankBy||'Unavailable')} / post</th></tr></thead><tbody>${a.formats.slice(0,10).map(f=>`<tr><td>${escape(f.format)}</td><td>${f.posts}</td><td>${f.average===null?'—':f.average.toFixed(1)}</td></tr>`).join('')}</tbody></table><h2>${h('Repeated themes and audience response','மீண்டும் வரும் கருப்பொருள்கள் & எதிர்வினை')}</h2><p>${escape(a.themes.slice(0,5).map(t=>`${t.theme} (${t.posts} posts)`).join(' · '))}</p><p>${h('Supplied likes, comments, shares and saves describe observed response. Demographics and causal explanations are unavailable.','வழங்கப்பட்ட likes, comments, shares, saves எதிர்வினையைக் காட்டுகின்றன. மக்கள்தொகை விவரங்களும் காரண விளக்கங்களும் கிடைக்கவில்லை.')}</p><p>${h('Interaction rate','எதிர்வினை விகிதம்')}: ${a.interactionRate===null?h('Unavailable','கிடைக்கவில்லை'):a.interactionRate.toFixed(2)+'%'}<br/><span class="note">(likes + comments + shares + saves) / sum of post reach × 100. Requires all five fields; zero denominator yields unavailable.</span></p>`);
 ideas.forEach((idea,i)=>pages.push(`${brand}<div class="kicker">${h('VIDEO IDEA','வீடியோ யோசனை')} ${i+1} / 6 · ${h('PROPOSAL','பரிந்துரை')}</div><h1>${escape(idea.title)}</h1><h2>${h('Why this idea','ஏன் இந்த யோசனை')}</h2><p>${escape(idea.reason)}</p><div class="hook">${escape(idea.hook)}</div><p>${escape(idea.format)} · ${escape(idea.duration)}</p><h2>${h('Scene-by-scene','காட்சி வாரியாக')}</h2><ol>${idea.scenes.map(s=>`<li>${escape(s)}</li>`).join('')}</ol><h2>${h('Voiceover / talking points','பேச வேண்டிய கருத்துகள்')}</h2><p>${escape(idea.voiceover)}</p><h2>${h('Caption and call to action','Caption & செயலழைப்பு')}</h2><p>${escape(idea.caption)}</p><p><strong>${escape(idea.cta)}</strong></p><h2>${h('Evaluate after publication','வெளியீட்டுக்குப் பின் மதிப்பீடு')}</h2><p>${escape(idea.metric)}</p>`));
 pages.push(`${brand}<div class="kicker">${h('NEXT STEPS & PROVENANCE','அடுத்த படிகள் & தரவு மூலம்')}</div><h1>${h('Make the next move deliberate.','அடுத்த படியை திட்டமிடுங்கள்.')}</h1><h2>${h('Prioritized next actions · proposals','முன்னுரிமை அடுத்த செயல்கள் · பரிந்துரைகள்')}</h2><ol><li>${h('Verify missing account-level fields and export coverage.','விடுபட்ட account அளவீடுகளையும் export தரவு கிடைப்பையும் சரிபார்க்கவும்.')}</li><li>${h('Produce one proposed video using the strongest observed theme.','கவனிக்கப்பட்ட சிறந்த கருப்பொருளில் ஒரு வீடியோவை உருவாக்கவும்.')}</li><li>${h('Collect reach and response at consistent post ages; compare before expanding.','ஒரே பதிவுவயதில் reach மற்றும் எதிர்வினையை சேகரித்து ஒப்பிடவும்.')}</li></ol><h2>${h('Data source','தரவு மூலம்')}</h2><p>${escape(a.source)} · owner-imported CSV<br/>${h('Retrieved','பெறப்பட்டது')}: ${escape(a.retrievedAt)}<br/>${h('Reporting period','அறிக்கை காலம்')}: ${escape(a.start)} → ${escape(a.end)} · ${escape(a.timezone)}</p><h2>${h('Limitations','வரம்புகள்')}</h2><ul>${a.limitations.map(l=>`<li>${escape(l)}</li>`).join('')}</ul><p class="note">${h('Prepared by LUCIFER. Review the data, layout and destination before approving delivery.','LUCIFER தயாரித்தது. அனுப்ப அனுமதிக்கும் முன் தரவு, வடிவமைப்பு, பெறுநர் ஆகியவற்றைச் சரிபார்க்கவும்.')}</p>`);
 return `<!doctype html><html lang="${language}"><head><meta charset="utf-8"/><style>@font-face{font-family:Inter;src:url(data:font/woff2;base64,${latin})}@font-face{font-family:Tamil;src:url(data:font/woff2;base64,${tamil})}*{box-sizing:border-box}body{margin:0;color:#282833;font-family:Inter,Tamil,sans-serif;font-size:${ta?'12':'13'}px;line-height:1.65} @page{size:A4;margin:0}.sheet{width:210mm;height:297mm;padding:16mm 18mm;position:relative;break-after:page;background:white}.sheet:last-child{break-after:auto}.content{width:100%;overflow-wrap:anywhere}.brand{color:#a82448;letter-spacing:3px;font-size:17px;margin-bottom:25px}.logo{max-width:140px;max-height:58px;object-fit:contain;margin-bottom:17px}.kicker{font-size:9px;letter-spacing:1.6px;color:#a82448;margin:18px 0}h1{font-size:${ta?'27':'34'}px;line-height:1.4;letter-spacing:-.5px;font-weight:500;white-space:pre-line;margin:18px 0 20px}h2{font-size:15px;color:#a82448;margin:22px 0 9px;font-weight:500}p{margin:9px 0 13px}.subtitle{font-size:18px}.note{font-size:10px;color:#73737d}table{width:100%;border-collapse:collapse;font-size:11px;table-layout:fixed}td,th{padding:9px 10px;text-align:left;border-bottom:1px solid #e8e5eb;overflow-wrap:anywhere}th{background:#f8edf2;font-weight:400;color:#8c2949}li{margin-bottom:12px;padding-left:6px}ol,ul{padding-left:19px}.hook{font-size:18px;padding:18px;background:#f8edf2;border-left:3px solid #a82448;margin:18px 0}footer{position:absolute;left:18mm;right:18mm;bottom:10mm;display:flex;justify-content:space-between;font-size:9px;color:#797781;border-top:1px solid #e9e7ec;padding-top:9px}@media screen{body{background:#ededf2}.sheet{margin:0 0 20px}}</style></head><body>${pages.map((content,i)=>`<section class="sheet"><div class="content">${content}</div><footer><span>${escape(a.brand)} · LUCIFER · ${escape(a.end)}</span><span>${i+1} / ${pages.length}</span></footer></section>`).join('')}</body></html>`;
}
