import type { Skill } from '../shared/contracts.js';
const skill=(id:string,purpose:string,inputs:string[],integrations:string[],permissions:string[],tools:string[],output:string,checks:string[],recovery:string,status='implemented'):Skill=>({id,purpose,inputs,integrations,permissions,tools,output,checks,recovery,status});
export const skills:Skill[]=[
  skill('research','Research with cited sources',['question'],['OpenAI web_search'],['model'],['web_search'],'Answer and source URLs',['Provider returned source annotations'],'Configure a supported model and enable web search','awaiting_configuration'),
  skill('documents','Read and summarize documents',['fileId','language'],['PDF.js','model for synthesis'],['files','model'],['read_file'],'Extracted text or model summary',['File exists','Text extracted; scanned PDFs flagged'],'Use text export when OCR is unavailable'),
  skill('analytics','Analyse social performance from actual exports',['CSV','account','period','timezone'],['user-provided CSV'],['files','reports'],['analyze_csv'],'Metrics, rankings, denominators, limitations',['Numeric fields valid','Dates in range','Missing values remain unavailable'],'Import the documented CSV schema'),
  skill('strategy','Prepare exactly six evidence-based video proposals',['analysis','brand'],[],['reports'],['create_report'],'Six full video briefs',['Exactly six','Reasons reference observed posts'],'Rule-based briefs available without a model'),
  skill('pdf','Render a branded English or Tamil PDF',['analysis','brand','logoId','language'],['Chromium','Noto Sans Tamil'],['reports'],['create_report'],'PDF and page previews',['Fonts loaded','Page count and text checked','Previews require visual approval'],'Install Chromium; report remains reviewable'),
  skill('telegram','Send an approved file to a verified destination',['fileId','verified destination'],['Telegram Bot API'],['telegram'],['send_document'],'Confirmed message_id or recoverable failure',['One-time destination verification','Persisted receipt','No automatic retry after uncertain send'],'Keep file; reconcile uncertain delivery before retry'),
  skill('files','Read, create and organize approved local files',['deviceId','folder alias','relative path'],['Windows companion'],['devices'],['read_file','write_document','move_file'],'Result from selected device',['Realpath boundary','No overwrite','Owner authorization for move'],'Reconnect and submit a fresh command'),
  skill('applications','Open approved apps and websites',['deviceId','app alias or URL'],['Windows companion'],['devices'],['open_app','open_website','open_project'],'OS launch result',['Executable allowlist','HTTPS website allowlist'],'Check companion config and connectivity'),
  skill('development','Inspect a selected project and run fixed approved commands',['deviceId','folder alias','command alias'],['Windows companion'],['devices'],['read_file','run_command'],'Exit code and bounded output',['Fixed executable and arguments','Timeout','Explicit owner approval'],'Review errors; commands are never automatically retried'),
  skill('reminders','Schedule persistent one-time or recurring reminders',['title','ISO date','timezone','channel'],['SQLite','in-app or Telegram'],['reminders'],['schedule_reminder'],'Schedule and separate delivery state',['Future date','Unique occurrence key','Restart recovery'],'Missed reminders deliver on next server start'),
];
