import type {FastifyInstance} from 'fastify';
import {randomBytes} from 'node:crypto';
import {z} from 'zod';
import {Store,now} from './store.js';
import {config} from './config.js';
import {hash} from './auth.js';
import type {Assistant} from './assistant.js';
import type {Files} from './files.js';
import type {Tasks} from './tasks.js';
import type {StoredFile} from '../shared/contracts.js';
import type {Report} from './reports.js';
export class DeliveryError extends Error {constructor(message:string,public uncertain=false){super(message);}}
export interface DeliveryChannel {send(key:string,method:'sendMessage'|'sendDocument',body:Record<string,string>,document?:{bytes:Buffer;name:string;type:string},signal?:AbortSignal):Promise<{messageId:number;chatId:string}>}
export class TelegramClient {
 constructor(public token=config.telegramToken,public transport:typeof fetch=fetch){}
 async call(method:string,body:Record<string,unknown>|FormData,signal?:AbortSignal){if(!this.token)throw new DeliveryError('Configure TELEGRAM_BOT_TOKEN on the server');let response:Response;
  try{response=await this.transport(`https://api.telegram.org/bot${this.token}/${method}`,{method:'POST',headers:body instanceof FormData?{}:{'Content-Type':'application/json'},body:body instanceof FormData?body:JSON.stringify(body),signal:signal?AbortSignal.any([signal,AbortSignal.timeout(25000)]):AbortSignal.timeout(25000)});}catch{throw new DeliveryError('Telegram network outcome is uncertain. Check the destination before retrying.',method.startsWith('send'));}
  let data:any;try{data=await response.json();}catch{throw new DeliveryError('Telegram response was unreadable; delivery outcome is uncertain.',method.startsWith('send'));}
  if(!data.ok){if(data.error_code===401)throw new DeliveryError('Telegram credentials expired or invalid. Replace the server token and verify the destination again.');if(data.error_code===403)throw new DeliveryError('Telegram access denied. Start or unblock the bot, then verify again.');throw new DeliveryError(`Telegram rejected the request (HTTP ${response.status}, code ${data.error_code||'unknown'}).`,response.status>=500&&method.startsWith('send'));}
  return data.result;
 }
}
export class Telegram implements DeliveryChannel {
 constructor(public store:Store,public assistant:Assistant,public files:Files,public tasks:Tasks,public client=new TelegramClient()){
  for(const receipt of store.list<any>('delivery'))if(receipt.state==='sending')store.put('delivery',{...receipt,state:'uncertain',error:'Server restarted during send; inspect Telegram before retrying.'});
 }
 enabled(destination=true){if(this.store.get<{stopped:boolean}>('control','emergency')?.stopped)throw new DeliveryError('Emergency stop is active');if(!this.assistant.settings().permissions.telegram)throw new DeliveryError('Telegram integration is disconnected');if(!this.client.token)throw new DeliveryError('Configure TELEGRAM_BOT_TOKEN on the server');const d=this.store.get<any>('integration','telegram');if(destination&&!d?.connected)throw new DeliveryError('Verify your Telegram destination in Skills & integrations');return d;}
 async send(key:string,method:'sendMessage'|'sendDocument',body:Record<string,string>,document?:{bytes:Buffer;name:string;type:string},signal?:AbortSignal){const destination=this.enabled();const receiptId=hash(`${key}:${destination.chatId}`);const existing=this.store.get<any>('delivery',receiptId);if(existing?.state==='confirmed')return existing.receipt;if(['sending','uncertain'].includes(existing?.state))throw new DeliveryError('Delivery is pending or uncertain. Reconcile it before another send.',true);
  signal?.throwIfAborted();this.store.put('delivery',{id:receiptId,key,chatId:destination.chatId,state:'sending',startedAt:now()});
  try{let payload:Record<string,unknown>|FormData={...body,chat_id:destination.chatId};if(document){const form=new FormData();form.set('chat_id',destination.chatId);for(const [k,v]of Object.entries(body))form.set(k,v);form.set('document',new Blob([new Uint8Array(document.bytes)],{type:document.type}),document.name);payload=form;}const result=await this.client.call(method,payload,signal);if(!Number.isInteger(result?.message_id)||result.message_id<=0)throw new DeliveryError('Telegram did not return a usable message identifier.',true);const receipt={messageId:result.message_id,chatId:String(result.chat.id)};this.store.put('delivery',{id:receiptId,key,chatId:destination.chatId,state:'confirmed',receipt,confirmedAt:now()});return receipt;}catch(e){this.store.put('delivery',{id:receiptId,key,chatId:destination.chatId,state:e instanceof DeliveryError&&e.uncertain?'uncertain':'failed',error:(e as Error).message});throw e;}
 }
 register(app:FastifyInstance){
  app.post('/api/telegram/challenge',async()=>{if(!this.client.token)throw new Error('Configure TELEGRAM_BOT_TOKEN in .env and restart the server');if(this.store.get<{stopped:boolean}>('control','emergency')?.stopped)throw new Error('Emergency stop is active');const bot=await this.client.call('getMe',{});const webhook=await this.client.call('getWebhookInfo',{});if(webhook.url)throw new Error('This bot uses a webhook. Use a dedicated LUCIFER bot, or remove that webhook deliberately before polling.');const telegramCode=randomBytes(18).toString('base64url'),expiresAt=new Date(Date.now()+300000).toISOString();this.store.put('verification',{id:'telegram',hash:hash(telegramCode),expiresAt,createdAt:now()});return {telegramCode,expiresAt,bot:bot.username,url:`https://t.me/${bot.username}?start=${telegramCode}`};});
  app.post('/api/telegram/verify',async()=>{const c=this.store.get<any>('verification','telegram');if(!c||Date.parse(c.expiresAt)<Date.now())throw new Error('Verification challenge expired. Create a new one.');const updates=await this.client.call('getUpdates',{timeout:0,allowed_updates:['message'],offset:this.store.get<any>('telegram_offset','owner')?.offset||0});let found:any;for(const u of updates){const m=u.message;if(m?.chat.type==='private'&&m.from?.id===m.chat.id&&m.date*1000>=Date.parse(c.createdAt)-1000&&m.text?.startsWith('/start ')&&hash(m.text.slice(7).trim())===c.hash)found=m;this.store.put('telegram_offset',{id:'owner',offset:u.update_id+1});}if(!found)throw new Error('No matching private /start verification message found yet. Send the code to your bot and retry.');const destination={id:'telegram',connected:true,chatId:String(found.chat.id),name:found.chat.first_name||found.chat.username||'Private Telegram chat',verifiedAt:now()};this.store.put('integration',destination);this.store.remove('verification','telegram');this.store.put('settings',{id:'owner',...this.assistant.settings(),permissions:{...this.assistant.settings().permissions,telegram:true}});return {connected:true,name:destination.name};});
  app.post('/api/telegram/send',async(req)=>{const {fileId}=z.object({fileId:z.uuid()}).strict().parse(req.body);const destination=this.enabled(),file=this.store.get<StoredFile>('file',fileId);if(!file)throw new Error('File not found');if(file.reportId){const report=this.store.get<Report>('report',file.reportId);if(report?.status!=='ready')throw new Error('Inspect and approve all PDF pages before delivery');}return this.tasks.run('Deliver '+file.name+' to '+destination.name,async(task,signal)=>{const bytes=await this.files.read(file.id);signal.throwIfAborted();this.tasks.event(task.id,'Delivering the authorized file to the verified Telegram destination.');const receipt=await this.send('file:'+file.id,'sendDocument',{caption:file.name},{bytes,name:file.name,type:file.type},signal);this.tasks.event(task.id,'Telegram confirmed message '+receipt.messageId+'.');return {fileId,receipt};});});
  app.post('/api/telegram/delivery/:id/reconcile',async(req)=>{const receiptId=(req.params as {id:string}).id;const body=z.object({outcome:z.enum(['not_received','received']),messageId:z.number().int().positive().nullable()}).strict().parse(req.body);const d=this.store.get<any>('delivery',receiptId);if(!d||d.state!=='uncertain')throw new Error('Only uncertain deliveries need reconciliation');if(body.outcome==='received'&&!body.messageId)throw new Error('Supply the observed Telegram message identifier');return this.store.put('delivery',{...d,state:body.outcome==='received'?'confirmed':'failed',receipt:body.outcome==='received'?{messageId:body.messageId,chatId:d.chatId}:undefined,reconciledBy:'owner',reconciledAt:now()});});
 }
}
