import assert from 'node:assert/strict';
import {randomBytes,createHash} from 'node:crypto';
import {readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import {Store} from '../server/store.js';
import {hash} from '../server/auth.js';
import {config} from '../server/config.js';
import {chromium} from 'playwright';
const store=new Store(config.dataDir),base='http://127.0.0.1:3001',session=randomBytes(32).toString('base64url');
store.db.prepare('INSERT INTO sessions VALUES(?,?)').run(hash(session),Date.now()+600000);
const headers={'Content-Type':'application/json','x-lucifer-request':'1',cookie:'lucifer_session='+session};
const request=async(route:string,method='GET',body?:unknown)=>{const response=await fetch(base+'/api/'+route,{method,headers,body:method==='GET'?undefined:JSON.stringify(body??{}),signal:AbortSignal.timeout(90000)});const value=await response.json() as any;if(!response.ok)throw new Error(route+': '+value.error);return value;};
const pause=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function task(taskId:string){const until=Date.now()+150000;while(Date.now()<until){const value=store.get<any>('task',taskId);if(value&&['completed','failed','cancelled','partially_completed','awaiting_input','awaiting_authorization'].includes(value.state))return value;await pause(250);}throw new Error('Task outcome was not confirmed before the verification deadline');}
const chat=async(text:string,fileIds:string[]=[])=>task((await request('chat','POST',{text,fileIds})).id);
const report:any={date:new Date().toISOString(),runtime:'Installed production backend and Windows companion',journeys:{},privateSpeechAccuracy:'Requires physical user test',telegramTestMessages:0};
const only=process.argv.find(argument=>argument.startsWith('--only='))?.slice(7);if(only){const previous=JSON.parse(await readFile('.local/verification/action-runtime-results.json','utf8'));report.journeys=previous.journeys;report.previousVerification=previous.date;}
const runId=Date.now(),filename='lucifer-action-check-'+runId+'.txt',marker='Harmless LUCIFER action check '+runId;
const protectedBefore=Object.fromEntries(await Promise.all(['ai-credentials.key','ai-credentials.enc','native/credential.bin'].map(async file=>[file,createHash('sha256').update(await readFile(path.join(config.dataDir,file))).digest('hex')])));
const check=async(name:string,work:()=>Promise<any>)=>{if(only&&name!==only)return;try{report.journeys[name]={passed:true,...await work()};console.log(name+': verified');}catch(error){report.journeys[name]={passed:false,error:(error as Error).message};console.log(name+': '+(error as Error).message);}};
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try{
 let ready=false;for(let attempt=0;attempt<90&&!ready;attempt++){try{const native=await request('native-voice');ready=native.devices.some((device:any)=>device.modelReady&&Date.now()-Date.parse(device.lastSeen)<10000);}catch{}if(!ready)await pause(1000);}assert.ok(ready,'Installed native worker/model heartbeat ready');
 await check('notepad',async()=>{const value=await chat('Open Notepad.');assert.equal(value.state,'completed');assert.ok(value.result.steps[0].output.accepted);return {confirmedWindowsLaunch:true,taskId:value.id};});
 await check('noteCreateFindRead',async()=>{const value=await chat(`Create note notes/${filename}: ${marker}; then find and read it.`);assert.equal(value.state,'completed',value.error||value.result?.reply);const operations=value.result.steps;assert.ok(operations.some((step:any)=>step.output.created===filename));assert.ok(operations.some((step:any)=>step.output.matches?.includes(filename)));assert.ok(operations.some((step:any)=>step.output.text===marker));assert.equal(await readFile(path.join(config.dataDir,'notes',filename),'utf8'),marker);return {path:'.local/notes/'+filename,verifiedCreateFindRead:true,route:'local validated multi-step tools',taskId:value.id};});
 await check('observedPublicWebsite',async()=>{const value=await chat('Open https://example.com and tell me what you see.');assert.equal(value.state,'completed',value.error||value.result?.reply);const observed=value.result.steps.find((step:any)=>step.output.url==='https://example.com/'&&typeof step.output.text==='string'&&step.output.text.length>0&&step.output.source==='Actual dedicated Windows browser DOM');assert.ok(observed,'Actual browser DOM observation required');assert.equal(observed.output.title,'Example Domain');assert.ok(Array.isArray(observed.output.headings));return {url:observed.output.url,title:observed.output.title,headings:observed.output.headings,observedAt:observed.output.observedAt,route:'local validated browser DOM observation',taskId:value.id};});
 await check('csvDownloadableReport',async()=>{const form=new FormData();form.append('file',new Blob(['item,quantity,price\napples,2,10\npears,3,20\n'],{type:'text/csv'}),'lucifer-sample-'+runId+'.csv');const response=await fetch(base+'/api/files',{method:'POST',headers:{'x-lucifer-request':'1',cookie:headers.cookie},body:form});assert.equal(response.status,200);const file=await response.json() as any;const value=await chat('Analyze the attached CSV and create a downloadable PDF report.',[file.id]);assert.equal(value.state,'completed',value.error);const result=value.result.steps[0].output;assert.equal(result.analysis.rows,2);assert.equal(result.analysis.columns.find((column:any)=>column.name==='quantity').sum,5);const downloaded=await fetch(base+result.download,{headers:{cookie:headers.cookie}});assert.equal(downloaded.status,200);const pdf=Buffer.from(await downloaded.arrayBuffer());assert.equal(pdf.subarray(0,5).toString(),'%PDF-');return {rows:2,quantitySum:5,fileId:result.fileId,download:result.download,verifiedPDF:true,taskId:value.id};});
 await check('reminderCreateCancel',async()=>{const at=new Date(Date.now()+3600000),timezone='Asia/Kolkata',parts=new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(at);const get=(key:string)=>parts.find(part=>part.type===key)!.value,localTime=`${get('year')}-${get('month')}-${get('day')}T${get('hour')}:${get('minute')}`;const title='LUCIFER harmless reminder '+runId;const value=await chat(`Remind me at ${localTime} in ${timezone} to ${title}; then cancel it.`);assert.equal(value.state,'completed',value.error||value.result?.reply);const reminder=store.list<any>('reminder').find(reminder=>reminder.title===title);assert.ok(reminder);assert.equal(reminder.status,'cancelled');return {createdAndCancelled:true,reminderId:reminder.id,route:'local validated reminder tools',taskId:value.id};});
 await check('contextualFollowUp',async()=>{const value=await chat('What was in that note?');assert.equal(value.state,'completed',value.error||value.result?.reply);assert.ok(value.result.reply.includes(filename));assert.ok(value.result.reply.includes(marker));return {filenameRecalled:true,contentsRecalled:true,route:'prior verified note reference plus actual read-back',taskId:value.id};});
 await check('cancelWithoutDuplicate',async()=>{const value=await request('chat','POST',{text:'Open Notepad.'});await request('tasks/'+value.id+'/cancel','POST');const result=await task(value.id);assert.equal(result.state,'cancelled');await pause(4000);const commands=store.list<any>('command').filter(command=>command.parentTaskId===value.id);assert.ok(commands.length<=1);assert.ok(commands.every(command=>command.status==='cancelled'));return {cancelled:true,commandsCreated:commands.length,noReplay:true,taskId:value.id};});
 if(process.argv.includes('--check-model'))await check('liveModelToolCheck',async()=>{const value=await chat('Use the current_time tool to read the actual system clock and briefly report its returned time. Do not guess.');assert.equal(value.state,'completed',value.error);assert.ok(value.result.steps.some((step:any)=>step.tool==='current_time'));return {actualModelToolCall:true,served:value.result.served,taskId:value.id};});
 if(only==='installedAppDiscovery')await check('installedAppDiscovery',async()=>{const value=await chat('Discover installed applications and list their launch aliases.');assert.equal(value.state,'completed',value.error);const result=value.result.steps[0].output;assert.ok(Array.isArray(result.apps));assert.ok(result.apps.length>0);return {observedLaunchTargets:result.apps.length,taskId:value.id};});
 await check('dashboardAndPermissions',async()=>{browser=await chromium.launch({headless:true});const context=await browser.newContext({viewport:{width:1440,height:1050}});await context.addCookies([{name:'lucifer_session',value:session,url:base}]);const page=await context.newPage(),errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.goto(base+'/#assistant');await page.getByRole('button',{name:'Talk to LUCIFER',exact:true}).waitFor();await page.getByRole('button',{name:'Test microphone',exact:true}).waitFor();await page.getByRole('button',{name:'Test speaker',exact:true}).waitFor();await page.getByRole('button',{name:'Permissions',exact:true}).click();await page.getByRole('heading',{name:'Capability list',exact:true}).waitFor();await page.screenshot({path:'.local/verification/action-permissions.png',fullPage:true});await page.getByRole('button',{name:'Assistant',exact:true}).click();await page.screenshot({path:'.local/verification/action-dashboard.png',fullPage:true});assert.deepEqual(errors,[]);return {visibleControls:true,permissionsVisible:true,browserErrors:errors};});
 for(const [file,digest] of Object.entries(protectedBefore))assert.equal(createHash('sha256').update(await readFile(path.join(config.dataDir,file))).digest('hex'),digest,'Existing encrypted credential preserved');report.credentialsPreserved=true;report.coreJourneysPassed=['notepad','noteCreateFindRead','observedPublicWebsite','csvDownloadableReport','reminderCreateCancel','contextualFollowUp','cancelWithoutDuplicate'].every(name=>report.journeys[name]?.passed);report.allPassed=Object.values(report.journeys).every((journey:any)=>journey.passed);await writeFile('.local/verification/action-runtime-results.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{await browser?.close();store.db.prepare('DELETE FROM sessions WHERE hash=?').run(hash(session));store.close();}
