import { useEffect,useState } from 'react';
import { api } from './api';
export function NativeVoicePanel({compact=false,onActivate}:{compact?:boolean;onActivate?:()=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let alive=true;const refresh=async()=>{try{const value=await api('/native-voice');if(alive){setData(value);setError('');}}catch(e){if(alive)setError((e as Error).message);}};void refresh();const timer=setInterval(refresh,3000);return()=>{alive=false;clearInterval(timer);};},[]);
 const control=async(deviceId:string,action:string)=>{if(busy)return;onActivate?.();setBusy(true);try{await api('/native-voice/'+deviceId+'/control','POST',{action});setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <section className={compact?'panel native-controls':'form-panel wide'} aria-label="Windows voice controls"><h3>{compact?'Talk and test':'Windows background voice'}</h3>
 {error&&<p role="alert" className="error">{error}</p>}
 {data?.devices?.length?data.devices.map((device:any)=>{const offline=Date.now()-Date.parse(device.lastSeen)>10000;return <div key={device.id}><p role="status"><strong>{offline?'Offline':device.state}</strong> · {device.detail} · microphone {device.microphone?'open':'closed'}</p><div className="row-actions"><button className="primary" disabled={busy||offline} onClick={()=>void control(device.id,'talk')}>Talk to LUCIFER</button><button disabled={busy||offline} onClick={()=>void control(device.id,'test-microphone')}>Test microphone</button><button disabled={busy||offline} onClick={()=>void control(device.id,'test-speaker')}>Test speaker</button><button disabled={busy||offline} onClick={()=>void control(device.id,device.microphone?'pause':'resume')}>{device.microphone?'Pause microphone':'Resume microphone'}</button><button className="danger" disabled={busy||offline} onClick={()=>void control(device.id,'stop')}>Stop</button>{!compact&&<button disabled={busy||offline} onClick={()=>void control(device.id,'settings')}>Voice settings and calibration</button>}</div>{device.transcript&&<p><strong>Local transcript:</strong> {device.transcript}</p>}{device.result&&<p><strong>Last spoken result:</strong> {device.result}</p>}<small>Windows laptop controls · {device.wakeHits||0} local wake detections · {device.phase||'Waiting'}</small></div>;}):<p>No Windows voice heartbeat. Browser/phone microphone remains available in the composer.</p>}
 {!compact&&<><p>Wake and transcription use local multilingual Whisper small/int8. Ambient transcripts stay local. Say “Lucifer, open Notepad” together, or say “Lucifer,” wait for the cue, then speak. English system voice and local Tamil eSpeak-NG are available.</p><p>Ctrl+Alt+Esc stops. Pause shortcut is shown in the tray. Starts after Windows sign-in while awake; phone browser voice is foreground only.</p></>}
 </section>;
}
