import {useEffect,useState} from 'react';
import type {AppState} from './App';
import {api} from './api';
export function PermissionsPanel({data,act}:{data:AppState;act:(work:()=>Promise<unknown>)=>Promise<void>}){
 const [scope,setScope]=useState<any>(null),[error,setError]=useState('');
 const load=async()=>{try{setScope(await api('/native-permissions'));setError('');}catch(e){setError((e as Error).message);}};
 useEffect(()=>{void load();const timer=setInterval(load,4000);return()=>clearInterval(timer);},[]);
 const update=(change:any)=>void act(async()=>{await api('/native-permissions','PUT',{browserAccess:scope.browserAccess,routineCommands:scope.routineCommands,...change});await load();});
 const native=data.devices.find((device:any)=>device.voiceAuthorized&&!device.revoked&&Date.now()-Date.parse(device.lastSeen)<15000);
 const permissions=data.settings.permissions;
 const capabilities=[['App launch / approved-folder notes',native&&permissions.devices?'ready':'setup required','Installed laptop, named aliases; exclusive new files.'],['Dedicated browser / web research',native&&scope?.browserAccess&&permissions.devices?'ready':'setup required','Actual page/links and source timestamps. Login/MFA completed privately.'],['General CSV / text / English and Tamil PDF',permissions.files&&permissions.reports?'ready':'setup required','Supplied inputs, calculated statistics, verified downloads.'],['In-app reminders',permissions.reminders?'ready':'setup required','Create/list/edit/cancel; browser-independent scheduling.'],['Telegram delivery',data.telegram?.connected?'ready':'setup required','Private bot token and owner-verified destination; exact send authorization.'],['Windows accessibility observation',native?'ready':'setup required','Actual supported window controls; generic arbitrary app manipulation unsupported.'],['Native Android automation','unsupported','Existing phone UI supports chat/foreground voice and approved laptop actions.'],['Scanned PDF OCR / arbitrary admin automation','unsupported','Text PDFs supported; no blanket elevated control.']];
 return <section className="page-content"><p>Routine reversible work runs within these grants. Important overwrite/move, sending, publishing, purchase, installation and access changes use an exact confirmation preview.</p>{error&&<p className="error" role="alert">{error}</p>}<div className="grid"><div className="form-panel"><h3>Laptop and browser</h3>{scope?.installed?<><label className="check"><input type="checkbox" checked={scope.routineCommands} onChange={e=>update({routineCommands:e.target.checked})}/>Execute routine chat commands on the authorized laptop</label><label className="check"><input type="checkbox" checked={scope.browserAccess} onChange={e=>update({browserAccess:e.target.checked})}/>Allow dedicated LUCIFER browser session</label><p>This session has its own browser profile. Logins/MFA stay in its browser; LUCIFER does not copy other profiles.</p><h4>Approved folders</h4>{Object.entries(scope.folders).map(([alias,folder])=><p key={alias}><strong>{alias}</strong><br/><code>{String(folder)}</code></p>)}<button disabled={!native} onClick={()=>void act(()=>api('/native-voice/'+native!.id+'/control','POST',{action:'grant-folder'}))}>Choose additional folder on Windows</button><h4>Approved apps</h4>{Object.keys(scope.apps).map(alias=><label className="check" key={alias}><input type="checkbox" checked onChange={()=>void act(async()=>{await api('/native-permissions/apps','POST',{alias,enabled:false});await load();})}/>{alias}</label>)}<button disabled={!native} onClick={()=>void act(()=>api('/chat','POST',{text:'Discover installed applications and list their launch aliases.'}))}>Discover installed apps</button>{scope.discovered.filter((app:any)=>!scope.apps[app.id]).map((app:any)=><div className="row-actions" key={app.id}><span>{app.name}</span><button onClick={()=>void act(async()=>{await api('/native-permissions/apps','POST',{alias:app.id,enabled:true});await load();})}>Approve launch</button></div>)}</>:<p>Install the existing Windows companion to configure scoped laptop access.</p>}</div><div className="form-panel"><h3>Tool and integration grants</h3>{Object.entries(permissions).map(([key,value])=><label className="check" key={key}><input type="checkbox" checked={value} onChange={e=>void act(()=>api('/settings','PUT',{...data.settings,permissions:{...permissions,[key]:e.target.checked}}))}/>{key}</label>)}<p>Revocation blocks new steps. Stop cancels running work; completed actions are not undone.</p></div></div><h2>Capability list</h2>{capabilities.map(([name,status,detail])=><div className="list-card" key={name}><h3>{name} <span className="pill">{status}</span></h3><p>{detail}</p></div>)}</section>;
}
