import {chromium,type BrowserContext,type Page,type ElementHandle} from 'playwright';
import path from 'node:path';
import {lookup} from 'node:dns/promises';
import {randomUUID} from 'node:crypto';
import type {Policy} from './policy.js';
import {redact} from '../server/auth.js';
let context:BrowserContext|undefined,page:Page|undefined;
const controls=new Map<string,{element:ElementHandle;url:string;operation:string;observed:{tag:string;name:string;href?:string;type?:string}}>();
export async function publicURL(value:string){const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password||url.port&&url.port!=='443')throw new Error('Browser tools accept public HTTPS only');const addresses=await lookup(url.hostname,{all:true});if(addresses.some(({address})=>/^(127\.|10\.|192\.168\.|169\.254\.|172\.(1[6-9]|2\d|3[01])\.|0\.|::1$|fc|fd|fe80|::ffff:)/i.test(address)))throw new Error('Private network/browser targets are blocked');return url.href;}
async function session(policy:Policy){if(!context){const spec=policy.apps.chrome||policy.apps.edge;if(!spec)throw new Error('A supported Chrome/Edge installation must be approved');context=await chromium.launchPersistentContext(path.resolve('.local/native/browser-profile'),{executablePath:spec.executable,headless:false,chromiumSandbox:true,args:['--no-first-run','--no-default-browser-check'],viewport:null});await context.route('**/*',async route=>{try{const url=route.request().url();if(url.startsWith('https:'))await publicURL(url);else if(!url.startsWith('data:')&&!url.startsWith('about:'))throw new Error();await route.continue();}catch{await route.abort();}});context.on('close',()=>{context=undefined;page=undefined;controls.clear();});}if(!page||page.isClosed())page=context.pages().find(candidate=>!candidate.isClosed())||await context.newPage();return page;}
export async function closeBrowser(){await context?.close().catch(()=>{});context=undefined;page=undefined;controls.clear();}
export async function browserAction(action:any,policy:Policy,signal:AbortSignal,ownerApproved=false){signal.throwIfAborted();const p=await session(policy);const abort=()=>{void p.close().catch(()=>{});page=undefined;};signal.addEventListener('abort',abort,{once:true});try{
 if(action.operation==='open'||action.operation==='search'){const url=await publicURL(action.operation==='search'?'https://duckduckgo.com/html/?q='+encodeURIComponent(action.query||''):action.url);await p.goto(url,{waitUntil:'domcontentloaded',timeout:30000});}
 if(['click','fill'].includes(action.operation)){const target=controls.get(action.reference);if(!target||target.url!==p.url())throw new Error('Observe the current page before using an actual control reference');const current=await target.element.evaluate((e:any)=>({tag:e.tagName,name:(e.innerText||e.getAttribute('aria-label')||e.getAttribute('placeholder')||'').slice(0,160),href:e.tagName==='A'?e.href:undefined,type:e.type}));if(JSON.stringify(current)!==JSON.stringify(target.observed))throw new Error('Control changed since observation; inspect it again before authorization');const control=await target.element.evaluate((e:any)=>({tag:e.tagName,label:e.innerText||e.getAttribute('aria-label')||e.name||'',href:e.tagName==='A'?e.href:'',type:e.type,method:e.form?.method||'',autocomplete:e.autocomplete||''}));if(/password|one.time|cc-|current-password|new-password/i.test(control.type+' '+control.autocomplete+' '+control.label))throw new Error('Complete private login/MFA/payment manually');const routine=action.operation==='click'&&control.tag==='A'&&control.href.startsWith('https:')||action.operation==='fill'&&control.method==='get'&&/search|query|\bq\b/i.test(control.label);if(!routine&&!ownerApproved)return {authorizationRequired:true,preview:{url:p.url(),control:control.label,operation:action.operation,text:action.text},detail:'Review this exact observed control before execution'};if(action.operation==='fill'){if(redact(action.text)!==action.text)throw new Error('Complete private login/MFA manually');await target.element.fill(action.text||'');}else await target.element.click({timeout:10000});await p.waitForTimeout(350);}
 signal.throwIfAborted();const url=await publicURL(p.url()),title=await p.title();
 if(await p.locator('input[type=password],input[autocomplete=one-time-code]').count())return {url,title,privateLoginRequired:true,detail:'Complete login/MFA privately in the dedicated browser. No form contents were read.'};
 const text=redact((await p.locator('body').innerText()).slice(0,16000)),headings=(await p.locator('h1,h2,h3').allInnerTexts()).slice(0,20).map(value=>redact(value.slice(0,300)));controls.clear();const observed:any[]=[];
 for(const element of (await p.$$('a[href],button,input:not([type=password])')).slice(0,50)){const data=await element.evaluate((e:any)=>({tag:e.tagName,name:(e.innerText||e.getAttribute('aria-label')||e.getAttribute('placeholder')||'').slice(0,160),href:e.tagName==='A'?e.href:undefined,type:e.type}));const reference=randomUUID();controls.set(reference,{element,url,operation:data.tag==='INPUT'?'fill':'click',observed:data});observed.push({reference,...data});}
 return {url,title,text,headings,controls:observed,observedAt:new Date().toISOString(),source:'Actual dedicated Windows browser DOM',untrusted:true};
 }finally{signal.removeEventListener('abort',abort);}}
