import path from 'node:path';
import { lstat,realpath,readFile,writeFile,copyFile,unlink,stat,readdir } from 'node:fs/promises';
import { constants } from 'node:fs';
import { spawn } from 'node:child_process';
import { z } from 'zod';
import { deviceActionSchema,type DeviceAction } from '../shared/contracts.js';
import { redact } from '../server/auth.js';
import { createHash } from 'node:crypto';
import { browserAction } from './browser.js';
import { discoverApps,observeApp } from './windows-tools.js';
const executableSchema=z.object({executable:z.string().min(1),args:z.array(z.string().max(300)).max(30)}).strict();
export const policySchema=z.object({server:z.url(),name:z.string().min(1).max(80),apps:z.record(z.string(),executableSchema),folders:z.record(z.string(),z.string()),websites:z.array(z.url()),allowHttpsWebsites:z.boolean().optional(),browserAccess:z.boolean().optional(),commands:z.record(z.string(),executableSchema.extend({folders:z.array(z.string())})),actions:z.array(z.enum(['open_app','open_website','open_project','read_file','find_files','write_document','move_file','run_command','edit_file','discover_apps','observe_app','browser_action','open_document']))}).strict();
export type Policy=z.infer<typeof policySchema>;
const privateComponent=/^(?:\.local|\.git|node_modules|\.env(?:\..*)?|ai-credentials\.(?:key|enc)|credential\.bin|lucifer\.db(?:-.*)?)$/i;
export function validateServer(server:string) {const url=new URL(server);if(url.username||url.password||url.search||url.hash)throw new Error('Server URL must not contain credentials or query strings');if(url.protocol!=='https:'&&!(url.protocol==='http:'&&['localhost','127.0.0.1','[::1]'].includes(url.hostname)))throw new Error('Remote companion connections require HTTPS');}
export async function scopedPath(root:string,relative:string,creating=false) {
  if(!relative||relative.length>300||/[\x00-\x1f:]/.test(relative)||/^[\\/]/.test(relative)||relative.split(/[\\/]/).some(p=>p==='..'||p==='.'||!p||p.endsWith('.')||p.endsWith(' ')||/^(con|prn|aux|nul|com\d|lpt\d)(\.|$)/i.test(p)))throw new Error('Unsafe relative path');
  if(relative.split(/[\\/]/).some(p=>privateComponent.test(p)))throw new Error('Private application state and credentials are not exposed by device file tools');
  const canonical=await realpath(root);const parts=relative.split(/[\\/]/);let current=canonical;
  for(let i=0;i<parts.length;i++){current=path.join(current,parts[i]);if(creating&&i===parts.length-1){try{await lstat(current);throw new Error('Destination already exists');}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}}else{const s=await lstat(current);if(s.isSymbolicLink())throw new Error('Symbolic links and junctions are not allowed');const resolved=await realpath(current);const delta=path.relative(canonical,resolved);if(delta.startsWith('..')||path.isAbsolute(delta))throw new Error('Path escapes approved folder');}}
  return current;
}
export async function runExecutable(spec:{executable:string;args:string[]},cwd:string|undefined,signal:AbortSignal,timeout=60000) {
  if(!path.isAbsolute(spec.executable)||/\.(cmd|bat|ps1|sh)$/i.test(spec.executable)||/(?:^|[\\/])(cmd|powershell|pwsh|bash|sh)(?:\.exe)?$/i.test(spec.executable))throw new Error('Only absolute native executables are permitted; shell interpreters and script launchers are blocked');
  await stat(spec.executable);signal.throwIfAborted();
  return new Promise<{exitCode:number|null;stdout:string;stderr:string}>((resolve,reject)=>{const child=spawn(spec.executable,spec.args,{cwd,shell:false,windowsHide:false,signal,detached:process.platform!=='win32'});let out='',err='';const stop=()=>{if(child.pid){if(process.platform==='win32')spawn('taskkill.exe',['/PID',String(child.pid),'/T','/F'],{shell:false});else try{process.kill(-child.pid,'SIGKILL');}catch{child.kill('SIGKILL');}}};const timer=setTimeout(stop,timeout);signal.addEventListener('abort',stop,{once:true});child.stdout.on('data',b=>{out=(out+b.toString()).slice(-32000);});child.stderr.on('data',b=>{err=(err+b.toString()).slice(-32000);});child.once('error',e=>{clearTimeout(timer);signal.removeEventListener('abort',stop);reject(e);});child.once('close',code=>{clearTimeout(timer);signal.removeEventListener('abort',stop);resolve({exitCode:code,stdout:redact(out),stderr:redact(err)});});});
}
export async function executeAction(policy:Policy,input:unknown,signal:AbortSignal,approve:(action:DeviceAction)=>Promise<boolean>) {
  const action=deviceActionSchema.parse(input);if(!policy.actions.includes(action.kind))throw new Error('Capability disabled on laptop');signal.throwIfAborted();
  const root='folder'in action?policy.folders[action.folder]:undefined;if('folder'in action&&!root)throw new Error('Folder alias not approved');
  if(['run_command','edit_file','move_file'].includes(action.kind)){if(!await approve(action))throw new Error('Local owner denied authorization');signal.throwIfAborted();}
  if(action.kind==='discover_apps')return discoverApps(signal);
  if(action.kind==='observe_app'){const app=policy.apps[action.app];if(!app)throw new Error('Application is not approved');return observeApp(app.executable,signal);}
  if(action.kind==='open_document'){if(!/\.(txt|md|csv)$/i.test(action.path))throw new Error('Only scoped text documents can be opened');const app=policy.apps[action.app];if(!app)throw new Error('Application is not approved');const file=await scopedPath(root!,action.path);if(!(await stat(file)).isFile())throw new Error('Choose a regular text file');return {...await windowsOpen(app.executable,signal,[...app.args,file]),detail:'Windows accepted the scoped document launch; use observe_app/read_file to verify.'};}
  if(action.kind==='browser_action'){if(!policy.browserAccess)throw new Error('Enable the dedicated browser session in Permissions first');return browserAction(action,policy,signal,await approve(action));}
  if(action.kind==='read_file'){const file=await scopedPath(root!,action.path);const s=await stat(file);if(s.size>1024*1024||!s.isFile())throw new Error('Only files up to 1 MB may be read');const bytes=await readFile(file);if(bytes.includes(0))throw new Error('Only UTF-8 text files may be read');return {text:redact(new TextDecoder('utf-8',{fatal:true}).decode(bytes)),hash:createHash('sha256').update(bytes).digest('hex'),bytes:s.size,source:action.folder+'/'+action.path};}
  if(action.kind==='edit_file'){if(!/\.(txt|csv|md)$/i.test(action.path))throw new Error('Only text, CSV and Markdown editing is supported');const file=await scopedPath(root!,action.path);const current=await readFile(file);if(createHash('sha256').update(current).digest('hex')!==action.expectedHash)throw new Error('File changed since preview; inspect it again before approving');signal.throwIfAborted();const backup=file+'.lucifer-backup-'+Date.now();await copyFile(file,backup,constants.COPYFILE_EXCL);await writeFile(file,action.text);return {edited:action.path,backup:path.basename(backup),hash:createHash('sha256').update(await readFile(file)).digest('hex'),verified:(await readFile(file,'utf8'))===action.text};}
  if(action.kind==='find_files'){const matches:string[]=[];let scanned=0;const walk=async(relative:string,depth:number)=>{signal.throwIfAborted();const directory=relative?await scopedPath(root!,relative):await realpath(root!);for(const entry of await readdir(directory,{withFileTypes:true})){if(++scanned>1000||matches.length>=50)return;if(entry.isSymbolicLink()||privateComponent.test(entry.name))continue;const next=relative?relative+'/'+entry.name:entry.name;if(entry.isDirectory()&&depth<3)await walk(next,depth+1);else if(entry.isFile()&&entry.name.toLowerCase().includes(action.query.toLowerCase()))matches.push(next);}};await walk('',0);return {folder:action.folder,matches,scanned,truncated:scanned>1000||matches.length>=50};}
  if(action.kind==='write_document'){if(!/\.(txt|csv|md)$/i.test(action.path))throw new Error('Generated local documents must be text, CSV or Markdown');const target=await scopedPath(root!,action.path,true);signal.throwIfAborted();await writeFile(target,action.text,{flag:'wx',mode:0o600});return {created:action.path,bytes:(await stat(target)).size,verified:(await readFile(target,'utf8'))===action.text};}
  if(action.kind==='move_file'){const source=await scopedPath(root!,action.path);const target=await scopedPath(root!,action.destination,true);if(!(await stat(source)).isFile())throw new Error('Only regular files may be organized');signal.throwIfAborted();await copyFile(source,target,constants.COPYFILE_EXCL);try{await unlink(source);}catch{throw new Error('Destination copied but source could not be removed; inspect both files.');}return {moved:action.path,destination:action.destination};}
  if(action.kind==='run_command'){const spec=policy.commands[action.command];if(!spec||!spec.folders.includes(action.folder))throw new Error('Command not approved for this project');const result=await runExecutable(spec,await realpath(root!),signal);if(result.exitCode!==0)throw new Error(`Command exit ${result.exitCode}\n${result.stderr}\n${result.stdout}`);return result;}
   if(action.kind==='open_website'){const url=new URL(action.url);if(url.protocol!=='https:'||url.username||url.password||(!policy.allowHttpsWebsites&&!policy.websites.some(w=>new URL(w).origin===url.origin)))throw new Error('HTTPS website origin not approved');if(process.platform!=='win32')throw new Error('Website opening requires the Windows companion');return windowsOpen(url.href,signal);}
  if(action.kind==='open_app'||action.kind==='open_project'){const spec=policy.apps[action.kind==='open_app'?action.app:'vscode'];if(!spec)throw new Error('Application alias is not approved');const args=action.kind==='open_project'?[...spec.args,await realpath(root!)]:spec.args;signal.throwIfAborted();if(!path.isAbsolute(spec.executable)||!spec.executable.toLowerCase().endsWith('.exe'))throw new Error('Approved app must be an absolute .exe path');await stat(spec.executable);const result=await windowsOpen(spec.executable,signal,args);return {...result,detail:'Windows accepted the launch request; window contents are not verified.'};}
  throw new Error('Unsupported action');
}
function windowsOpen(target:string,signal:AbortSignal,args:string[]=[]) {if(process.platform!=='win32')throw new Error('Application opening requires Windows');const script="$x=[Console]::In.ReadToEnd()|ConvertFrom-Json; if($x.args.Count -gt 0){$p=Start-Process -FilePath $x.target -ArgumentList $x.args -PassThru -ErrorAction Stop}else{$p=Start-Process -FilePath $x.target -PassThru -ErrorAction Stop}; @{accepted=$true;processId=$p.Id}|ConvertTo-Json -Compress";return new Promise<Record<string,unknown>>((resolve,reject)=>{const child=spawn('powershell.exe',['-NoProfile','-NonInteractive','-Command',script],{shell:false,signal});let out='',err='';child.stdout.on('data',b=>out+=b);child.stderr.on('data',b=>err+=b);child.on('error',reject);child.on('close',code=>code===0?resolve(JSON.parse(out)):reject(new Error(redact(err))));child.stdin.end(JSON.stringify({target,args:args.map(a=>'"'+a.replaceAll('"','')+'"')}));});}
